package openapi

// OperationDoc holds documentation for one API operation (method + path).
// Used by the generator to fill summary, description, and response codes in the OpenAPI spec.
type OperationDoc struct {
	Method      string // GET, POST, etc.
	Path        string // e.g. /api/games (path params as {id})
	Summary     string // Short one-line summary for the operation.
	Description string // Longer description; optional.
	// RequestBodyDoc describes the request body for POST/PUT/PATCH. Empty means no body or optional.
	RequestBodyDoc string
	// ResponseDocs keyed by status code ("200", "202", "400", "404", "500"). Description for that response.
	ResponseDocs map[string]string
}

// Operations returns documentation for all public API operations.
// Paths must match the routes registered in http.BuildRouter (use {id} for path params).
func Operations() []OperationDoc {
	return []OperationDoc{
		{
			Method:       "GET",
			Path:         "/health",
			Summary:      "Health check",
			Description:  "Returns 200 OK if the server is running. No body.",
			ResponseDocs: map[string]string{"200": "Server is healthy"},
		},
		{
			Method:      "GET",
			Path:        "/api/games",
			Summary:     "List games (paginated)",
			Description: "Returns total, page, page_size and games[] as full detail objects (same shape as GET /api/games/{id}/detail) for library grids/tables. Query: page (0-based, default 0), page_size (default 100, max 2000). page_size=0 requests all games in one response (rejected if library exceeds 20000 games; use pagination). Totals also available via GET /api/stats (canonical_game_count).",
			ResponseDocs: map[string]string{
				"200": "ListGamesResponse: total, page, page_size, games (GameDetailResponse[])",
				"400": "Invalid query or library too large for page_size=0",
				"500": "Internal server error",
			},
		},
		{
			Method:       "DELETE",
			Path:         "/api/games",
			Summary:      "Delete all games",
			Description:  "Removes all games and their files from the database. Use before a full rescan to start fresh.",
			ResponseDocs: map[string]string{"200": "All games deleted", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/{id}",
			Summary:      "Get game by ID",
			Description:  "Returns full game detail (same JSON as GET /api/games/{id}/detail and each element of GET /api/games).",
			ResponseDocs: map[string]string{"200": "GameDetailResponse", "404": "Game not found", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/{id}/detail",
			Summary:      "Get game detail",
			Description:  "Full metadata, media (with local_path/hash when known), external IDs, merged files, unified Xbox/xCloud fields (is_game_pass, xcloud_available, store_product_id, xcloud_url when present), and all source games with resolver_matches. Source records also include generic delivery metadata per profile (`delivery.profiles`) so clients can decide whether a source is direct, materialized, or unavailable. Legacy browser-play fields remain as a compatibility shim.",
			ResponseDocs: map[string]string{"200": "Game detail object", "404": "Game not found", "500": "Internal server error"},
		},
		{
			Method:         "PUT",
			Path:           "/api/games/{id}/cover-override",
			Summary:        "Set game cover override",
			Description:    "Pins one existing media asset that is already linked to the canonical game as the preferred cover. The server rejects media assets that are not linked to the requested game.",
			RequestBodyDoc: "JSON: { media_asset_id: number }",
			ResponseDocs:   map[string]string{"200": "Updated GameDetailResponse", "400": "Invalid request body or media_asset_id", "404": "Game not found", "422": "Media asset is not linked to this game", "500": "Internal server error"},
		},
		{
			Method:       "DELETE",
			Path:         "/api/games/{id}/cover-override",
			Summary:      "Clear game cover override",
			Description:  "Removes a pinned cover override for the canonical game and returns the updated game detail using normal cover selection again.",
			ResponseDocs: map[string]string{"200": "Updated GameDetailResponse", "404": "Game not found", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/games/{id}/refresh-metadata",
			Summary:      "Refresh metadata for one canonical game",
			Description:  "Runs the strict metadata/media refresh flow for one canonical game. Provider failures abort the refresh and return a fast-fail error instead of partial persistence.",
			ResponseDocs: map[string]string{"200": "Updated GameDetailResponse", "404": "Game not found", "409": "No eligible source records remain for refresh", "422": "Metadata providers unavailable or refresh failed fast", "500": "Internal server error"},
		},
		{
			Method:       "DELETE",
			Path:         "/api/games/{id}/sources/{source_game_id}",
			Summary:      "Hard delete one source record",
			Description:  "Deletes exactly one eligible file-backed source record, including provider-backed files and dependent database rows, then recomputes canonical grouping. The action never deletes sibling source records implicitly.",
			ResponseDocs: map[string]string{"200": "DeleteSourceGameResponse", "404": "Game or source record not found", "409": "Source record is not eligible for hard delete", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/{id}/play",
			Summary:      "Stream one game file by file_id",
			Description:  "Streams a single file that belongs to the requested canonical game. Requires query param file_id (stable id from game detail/list file metadata). Direct local sources stream immediately; materialized sources such as SMB/Drive require `profile` so the server can open the prepared cached file. Supports GET, HEAD, and Range requests via http.ServeContent.",
			ResponseDocs: map[string]string{"200": "Binary stream", "400": "Missing or invalid file_id", "404": "Game, file, source path, or prepared cache file not found", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/games/{id}/cache/prepare",
			Summary:        "Prepare cached source files for one delivery profile",
			Description:    "Starts or reuses a cache/materialization job for one source record and delivery profile. Direct sources may return an immediate completed response; remote materializable sources return 202 while the job downloads into the reusable source cache.",
			RequestBodyDoc: "JSON: { source_game_id: string, profile: string }",
			ResponseDocs:   map[string]string{"200": "CachePrepareResponse JSON; source already ready or direct", "202": "CachePrepareResponse JSON; job accepted", "400": "Invalid game id, source_game_id, or profile", "404": "Game not found", "503": "Cache service unavailable"},
		},
		{
			Method:       "GET",
			Path:         "/api/cache/jobs",
			Summary:      "List recent cache prepare jobs",
			Description:  "Returns recent cache prepare/materialization jobs in reverse-updated order. Query: limit (optional, defaults to 25).",
			ResponseDocs: map[string]string{"200": "JSON object with jobs[] of SourceCacheJobStatus", "500": "Internal server error", "503": "Cache service unavailable"},
		},
		{
			Method:       "GET",
			Path:         "/api/cache/jobs/{job_id}",
			Summary:      "Get one cache prepare job",
			Description:  "Returns persisted status for one cache prepare/materialization job, including progress, terminal error, and entry linkage when ready.",
			ResponseDocs: map[string]string{"200": "SourceCacheJobStatus JSON", "400": "job_id is required", "404": "Job not found", "500": "Internal server error", "503": "Cache service unavailable"},
		},
		{
			Method:       "GET",
			Path:         "/api/cache/entries",
			Summary:      "List cached source entries",
			Description:  "Returns all reusable cache entries with operator-facing metadata such as integration label, source context, profile, status, size, and timestamps.",
			ResponseDocs: map[string]string{"200": "JSON object with entries[] of cache entry DTOs", "500": "Internal server error", "503": "Cache service unavailable"},
		},
		{
			Method:       "DELETE",
			Path:         "/api/cache/entries/{entry_id}",
			Summary:      "Evict one cached source entry",
			Description:  "Deletes one cache entry, its tracked files, and the materialized files on disk.",
			ResponseDocs: map[string]string{"204": "Entry deleted", "400": "entry_id is required", "500": "Internal server error", "503": "Cache service unavailable"},
		},
		{
			Method:       "POST",
			Path:         "/api/cache/clear",
			Summary:      "Clear all cached source entries",
			Description:  "Deletes all reusable cache entries and removes the materialized cache root contents.",
			ResponseDocs: map[string]string{"200": "Status ok JSON", "500": "Internal server error", "503": "Cache service unavailable"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/{id}/save-sync/slots",
			Summary:      "List save-sync slots for one browser runtime source",
			Description:  "Returns local cached summary metadata for save-sync slots for the requested canonical game, source game, runtime, and save-sync integration. Query params: integration_id, source_game_id, runtime.",
			ResponseDocs: map[string]string{"200": "JSON object with slots[] of SaveSyncSlotSummary", "400": "Missing or invalid integration_id, source_game_id, or runtime", "404": "Game not found", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/games/{id}/save-sync/prefetch",
			Summary:        "Prefetch save-sync slots into the local cache",
			Description:    "Starts a background prefetch of EmulatorJS save-sync slots from the active remote integration into the server local cache. Missing remote slots are cached as empty; provider failures fail the job.",
			RequestBodyDoc: "JSON: { integration_id, source_game_id, runtime }",
			ResponseDocs:   map[string]string{"202": "SaveSyncPrefetchStatus JSON", "400": "Invalid parameters", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/{id}/save-sync/slots/{slot_id}",
			Summary:      "Get one cached save-sync slot snapshot",
			Description:  "Loads the manifest metadata and opaque zip snapshot for one browser-runtime save slot from the server local cache. Query params: integration_id, source_game_id, runtime.",
			ResponseDocs: map[string]string{"200": "SaveSyncSnapshot JSON", "400": "Missing or invalid parameters", "404": "Slot or game not found", "500": "Internal server error"},
		},
		{
			Method:         "PUT",
			Path:           "/api/games/{id}/save-sync/slots/{slot_id}",
			Summary:        "Store one save-sync slot snapshot",
			Description:    "Stores a whole runtime save snapshot into the local server cache and queues a cloud upload. The server validates ownership, runtime compatibility, file manifest integrity, and optional conflict state via `base_manifest_hash`. Use `force=true` to overwrite after a conflict warning.",
			RequestBodyDoc: "JSON: { integration_id, source_game_id, runtime, base_manifest_hash?, force?, snapshot: { canonical_game_id?, source_game_id?, runtime?, slot_id?, files[], archive_base64 } }",
			ResponseDocs:   map[string]string{"200": "SaveSyncPutResult JSON", "400": "Invalid parameters or snapshot payload", "404": "Game or slot target not found", "409": "SaveSyncPutResult with conflict metadata", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/media/{assetID}",
			Summary:      "Stream cached media file",
			Description:  "Serves a file from MEDIA_ROOT using media_assets.id and the row's local_path (must be relative, no '..'). Set MEDIA_ROOT in config (default ./media). Use media[].asset_id from game detail; supports Range requests via http.ServeContent.",
			ResponseDocs: map[string]string{"200": "Binary stream", "400": "Invalid id", "404": "Unknown asset or missing file", "500": "Internal server error"},
		},
		{
			Method:         "PUT",
			Path:           "/api/media/{assetID}/metadata",
			Summary:        "Backfill media dimensions",
			Description:    "Stores probed width/height metadata for an existing media asset so future clients can make layout decisions without probing again.",
			RequestBodyDoc: "JSON: { width: number, height: number, mime_type?: string }",
			ResponseDocs:   map[string]string{"204": "Metadata updated", "400": "Invalid id or body", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/stats",
			Summary:      "Library statistics",
			Description:  "Single JSON document: canonical and source game counts, breakdowns by platform/kind/integration/plugin, metadata coverage, decade and genre summaries, and canonical-game coverage for media and achievements.",
			ResponseDocs: map[string]string{"200": "LibraryStats JSON", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/about",
			Summary:      "Application build metadata",
			Description:  "Returns the server's authoritative app version information, including version, commit, build date, and author credits.",
			ResponseDocs: map[string]string{"200": "AboutInfo JSON", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/about/license",
			Summary:      "Open-source license text",
			Description:  "Streams the repository license file used by the About page.",
			ResponseDocs: map[string]string{"200": "License text", "500": "License file not found"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/{id}/achievements",
			Summary:      "Get achievements for a game",
			Description:  "Fetches achievements on-demand from all achievement-capable plugins that have an external ID match for this game. Returns an array of achievement sets, one per source (steam, xbox, retroachievements).",
			ResponseDocs: map[string]string{"200": "Array of achievement sets", "400": "id required", "404": "Game not found", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/achievements",
			Summary:      "Get cached achievements dashboard",
			Description:  "Returns cached achievement totals by system and by canonical game. This endpoint only reads stored achievement cache rows and does not fetch achievements from external integrations.",
			ResponseDocs: map[string]string{"200": "AchievementsDashboardResponse", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/achievements/explorer",
			Summary:      "Get cached achievements explorer",
			Description:  "Returns cached achievement sets and achievement rows grouped by canonical game. This endpoint is read-only over stored cache rows and does not trigger provider fetches.",
			ResponseDocs: map[string]string{"200": "AchievementsExplorerResponse", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/scan",
			Summary:        "Run scan",
			Description:    "Starts an asynchronous scan job. Runs discovery: calls each source plugin (source.library.list) and, for integrations with root_path in config, runs the local inventory pipeline. Optional body limits which sources to scan or requests metadata-only refresh.",
			RequestBodyDoc: "Optional JSON: { \"game_sources\": [\"integration-id-1\", ...], \"metadata_only\": true|false }. Omitted or empty game_sources = scan all sources.",
			ResponseDocs: map[string]string{
				"202": "ScanJobStatus JSON",
				"400": "Invalid JSON body",
				"409": "Another scan job is already active; returns the active ScanJobStatus",
				"500": "Internal server error",
			},
		},
		{
			Method:      "GET",
			Path:        "/api/scan",
			Summary:     "Run full scan",
			Description: "Same as POST /api/scan with no body: starts an asynchronous full-library scan job across all game source integrations.",
			ResponseDocs: map[string]string{
				"202": "ScanJobStatus JSON",
				"409": "Another scan job is already active; returns the active ScanJobStatus",
				"500": "Internal server error",
			},
		},
		{
			Method:       "GET",
			Path:         "/api/scan/jobs/{job_id}",
			Summary:      "Get scan job status",
			Description:  "Returns the current in-memory status for an asynchronous scan job, including state, integration-level progress snapshots, a rolling recent-events log, current integration, report id, and any terminal error.",
			ResponseDocs: map[string]string{"200": "ScanJobStatus JSON", "400": "job_id is required", "404": "Unknown job id", "500": "Internal server error"},
		},
		{
			Method:      "POST",
			Path:        "/api/scan/jobs/{job_id}/cancel",
			Summary:     "Cancel a running scan job",
			Description: "Requests cancellation for an asynchronous scan job. Returns the updated ScanJobStatus. Jobs transition through cancelling and then cancelled if the worker exits due to context cancellation.",
			ResponseDocs: map[string]string{
				"200": "ScanJobStatus JSON; job was already cancelling or cancelled",
				"202": "ScanJobStatus JSON; cancellation requested",
				"400": "job_id is required",
				"404": "Unknown job id",
				"409": "ScanJobStatus JSON; job is already completed or failed",
				"500": "Internal server error",
			},
		},
		{
			Method:      "GET",
			Path:        "/api/scan/reports",
			Summary:     "List recent scan reports",
			Description: "Returns the most recent persisted scan reports in reverse chronological order. Query: limit (optional, defaults to 10). Each report includes totals plus per-integration diff summaries.",
			ResponseDocs: map[string]string{
				"200": "Array of ScanReport JSON objects",
				"500": "Internal server error",
			},
		},
		{
			Method:       "GET",
			Path:         "/api/scan/reports/{id}",
			Summary:      "Get one scan report",
			Description:  "Returns one persisted scan report by id, including totals, timing, metadata_only flag, and per-integration results.",
			ResponseDocs: map[string]string{"200": "ScanReport JSON", "400": "id is required", "404": "Report not found", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/plugins",
			Summary:      "List plugins",
			Description:  "Returns the list of discovered plugins with ID, version, and capabilities.",
			ResponseDocs: map[string]string{"200": "Array of plugin descriptors", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/plugins/{plugin_id}",
			Summary:      "Get plugin by ID",
			Description:  "Returns a single plugin's descriptor including config schema.",
			ResponseDocs: map[string]string{"200": "Plugin info", "400": "plugin_id required", "404": "Plugin not found", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/config/frontend",
			Summary:      "Get frontend preferences",
			Description:  "Returns stored SPA preferences as a JSON object; {} if unset or invalid.",
			ResponseDocs: map[string]string{"200": "JSON object", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/config/frontend",
			Summary:        "Set frontend preferences",
			Description:    "Upserts SPA preferences as a single JSON object (theme, layout, active save-sync integration, etc.). Stored under key frontend.",
			RequestBodyDoc: "JSON object (any keys). Max size enforced by server.",
			ResponseDocs:   map[string]string{"200": "Saved", "400": "Not a JSON object or too large", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/config/{key}",
			Summary:        "Set config value",
			Description:    "Upserts a configuration value by key (e.g. google_drive_creds).",
			RequestBodyDoc: "JSON: { \"value\": \"string\" }",
			ResponseDocs:   map[string]string{"200": "Value set", "400": "Invalid body", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/integrations",
			Summary:      "List integrations",
			Description:  "Returns all configured integrations (plugin instances) with id, plugin_id, label, integration_type, config.",
			ResponseDocs: map[string]string{"200": "Array of integrations", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/integrations/status",
			Summary:      "Integration status",
			Description:  "Returns status for each integration (ok, error, unavailable) by calling plugin.check_config.",
			ResponseDocs: map[string]string{"200": "Array of { integration_id, plugin_id, label, status, message }", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/integrations",
			Summary:        "Create integration",
			Description:    "Creates a new integration (plugin instance). Validates config against plugin schema and plugin.check_config before persisting.",
			RequestBodyDoc: "JSON: { \"plugin_id\": \"string\", \"label\": \"string\", \"integration_type\": \"source\"|\"metadata\"|..., \"config\": {} }",
			ResponseDocs: map[string]string{
				"201": "Integration created (body is the integration)",
				"400": "Validation error (missing/invalid plugin_id, label, integration_type, or config)",
				"409": "duplicate_integration: same plugin_id and equivalent config JSON (body includes integration_id and integration)",
				"500": "Internal server error",
			},
		},
		{
			Method:       "GET",
			Path:         "/api/integrations/{id}/status",
			Summary:      "Validate one integration",
			Description:  "Runs plugin.check_config for one saved integration and returns a single IntegrationStatusEntry with status, label, and message.",
			ResponseDocs: map[string]string{"200": "IntegrationStatusEntry JSON", "400": "id is required", "404": "Integration not found", "500": "Internal server error"},
		},
		{
			Method:      "POST",
			Path:        "/api/integrations/{id}/authorize",
			Summary:     "Start or resume OAuth for one integration",
			Description: "Validates the saved config for one integration and either returns its current status or, when browser consent is still required, returns the same oauth_required payload used by create so the frontend can open the authorization URL.",
			ResponseDocs: map[string]string{
				"200": "IntegrationStatusEntry JSON when no browser auth step is needed",
				"202": "OAuthRequiredResponse JSON with authorize_url and state",
				"400": "Invalid id or saved config",
				"404": "Integration not found",
				"500": "Internal server error",
			},
		},
		{
			Method:       "GET",
			Path:         "/api/integrations/{id}/games",
			Summary:      "List games discovered by one source integration",
			Description:  "Returns lightweight canonical game rows for games linked to the specified source integration. Intended for Settings drill-down lists and quick inspection.",
			ResponseDocs: map[string]string{"200": "Array of GameListItem JSON", "400": "id is required", "404": "Integration not found", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/integrations/{id}/enriched-games",
			Summary:      "List games enriched by one metadata integration",
			Description:  "Resolves the saved integration to its plugin_id and returns lightweight canonical game rows enriched by that metadata provider's plugin.",
			ResponseDocs: map[string]string{"200": "Array of GameListItem JSON", "400": "id is required", "404": "Integration not found", "500": "Internal server error"},
		},
		{
			Method:      "GET",
			Path:        "/api/review-candidates",
			Summary:     "List manual-review candidates",
			Description: "Returns manual-review candidate summaries for the Undetected Games workflow. Query: scope (active or archive, default active) and limit (optional). Review state can be pending, matched, or not_a_game.",
			ResponseDocs: map[string]string{
				"200": "Array of ManualReviewCandidateSummary JSON",
				"400": "Invalid scope or limit",
				"500": "Internal server error",
			},
		},
		{
			Method:       "GET",
			Path:         "/api/review-candidates/{id}",
			Summary:      "Get one manual-review candidate",
			Description:  "Returns full manual-review candidate detail including files, resolver matches, current review_state, and linked canonical game id when present.",
			ResponseDocs: map[string]string{"200": "ManualReviewCandidateDetail JSON", "400": "id is required", "404": "Candidate not found", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/review-candidates/redetect",
			Summary:      "Re-detect active manual-review candidates",
			Description:  "Runs the strict automatic metadata re-detect workflow for all active pending manual-review candidates. Provider or workflow errors fail fast and return partial batch counts plus the candidate id that aborted the run.",
			ResponseDocs: map[string]string{"200": "ManualReviewRedetectBatchResult JSON", "500": "Fail-fast batch error with partial ManualReviewRedetectBatchResult JSON"},
		},
		{
			Method:         "POST",
			Path:           "/api/review-candidates/{id}/search",
			Summary:        "Search metadata providers for a review candidate",
			Description:    "Runs a manual search across configured metadata providers for one candidate. If query is omitted, the server derives a best-effort title query from the candidate data.",
			RequestBodyDoc: "Optional JSON: { query?: string }",
			ResponseDocs:   map[string]string{"200": "ManualReviewSearchResponse JSON", "400": "Invalid body or missing id", "404": "Candidate not found", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/review-candidates/{id}/redetect",
			Summary:      "Re-detect one manual-review candidate",
			Description:  "Runs strict automatic metadata identify, consensus, and fill for one pending manual-review candidate. Identified results persist through the normal scan refresh path; unidentified results leave the candidate pending.",
			ResponseDocs: map[string]string{"200": "ManualReviewRedetectResponse JSON", "400": "Missing id or candidate not eligible", "404": "Candidate not found", "500": "Metadata providers unavailable or internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/review-candidates/{id}/apply",
			Summary:        "Apply a manual-review search result",
			Description:    "Persists a chosen manual-review metadata match for the candidate, marks review_state as matched, and updates the candidate detail that the UI should continue showing.",
			RequestBodyDoc: "JSON manual-review search result object (provider ids, external_id, title, optional metadata fields).",
			ResponseDocs:   map[string]string{"200": "Updated ManualReviewCandidateDetail JSON", "400": "Invalid body or missing id", "404": "Candidate not found", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/review-candidates/{id}/not-a-game",
			Summary:      "Archive a candidate as not a game",
			Description:  "Marks the candidate review_state as not_a_game and moves it out of the active Undetected Games queue while preserving the decision for later scan refreshes.",
			ResponseDocs: map[string]string{"200": "Updated ManualReviewCandidateDetail JSON", "400": "Missing id", "404": "Candidate not found", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/review-candidates/{id}/unarchive",
			Summary:      "Restore an archived manual-review candidate",
			Description:  "Moves an archived candidate back into the active queue and resets its review_state to pending so it can be worked again.",
			ResponseDocs: map[string]string{"200": "Updated ManualReviewCandidateDetail JSON", "400": "Missing id", "404": "Candidate not found", "500": "Internal server error"},
		},
		{
			Method:         "PUT",
			Path:           "/api/integrations/{id}",
			Summary:        "Update one integration",
			Description:    "Updates selected integration fields. Label and integration_type are merged when present; config is optional but, when supplied, must remain a JSON object that passes schema validation and plugin.check_config. OAuth-backed plugins may return oauth_required so the frontend can complete consent before retrying the save.",
			RequestBodyDoc: "JSON: { label?, integration_type?, config? }",
			ResponseDocs: map[string]string{
				"200": "Updated integration JSON",
				"202": "OAuthRequiredResponse JSON with authorize_url and state",
				"400": "Invalid id, JSON body, or config",
				"404": "Integration not found",
				"500": "Internal server error",
			},
		},
		{
			Method:       "DELETE",
			Path:         "/api/integrations/{id}",
			Summary:      "Delete one integration",
			Description:  "Deletes the integration. If the plugin has source capability, the server also cascade-deletes associated source games and related child rows before removing the integration.",
			ResponseDocs: map[string]string{"204": "Integration deleted", "400": "id is required", "404": "Integration not found", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/plugins/{plugin_id}/browse",
			Summary:        "Browse source paths via a plugin",
			Description:    "Proxies a source.browse IPC call to a plugin so the frontend can browse remote/local path trees during integration setup.",
			RequestBodyDoc: "JSON: { path: string }",
			ResponseDocs:   map[string]string{"200": "Plugin-defined browse result JSON", "400": "plugin_id required or invalid body", "500": "Browse failed"},
		},
		{
			Method:       "GET",
			Path:         "/api/sync/status",
			Summary:      "Get sync configuration status",
			Description:  "Returns whether settings sync is configured, whether an encrypted key/passphrase is already stored locally, and timestamps for the last push and pull operations when known.",
			ResponseDocs: map[string]string{"200": "SyncStatus JSON", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/sync/push",
			Summary:        "Push settings sync snapshot",
			Description:    "Exports the local sync payload and uploads it through the configured sync integration. Optional passphrase in the body overrides any stored key for this request.",
			RequestBodyDoc: "Optional JSON: { passphrase?: string }",
			ResponseDocs:   map[string]string{"200": "PushResult JSON", "400": "Invalid JSON body", "500": "Sync push failed"},
		},
		{
			Method:         "POST",
			Path:           "/api/sync/pull",
			Summary:        "Pull and merge settings sync snapshot",
			Description:    "Downloads the latest remote sync payload, decrypts it, and merges integrations/settings into the local database. Optional passphrase in the body overrides any stored key for this request.",
			RequestBodyDoc: "Optional JSON: { passphrase?: string }",
			ResponseDocs:   map[string]string{"200": "PullResult JSON", "400": "Invalid JSON body", "500": "Sync pull failed"},
		},
		{
			Method:         "POST",
			Path:           "/api/sync/key",
			Summary:        "Store sync passphrase locally",
			Description:    "Stores the sync passphrase/key for later push/pull operations so the frontend does not need to resend it every time.",
			RequestBodyDoc: "JSON: { passphrase: string }",
			ResponseDocs:   map[string]string{"200": "Status ok JSON", "400": "Invalid JSON body or missing passphrase", "500": "Failed to store sync key"},
		},
		{
			Method:       "DELETE",
			Path:         "/api/sync/key",
			Summary:      "Clear stored sync passphrase",
			Description:  "Deletes the locally stored sync key/passphrase without changing remote data.",
			ResponseDocs: map[string]string{"200": "Status ok JSON", "500": "Failed to clear sync key"},
		},
		{
			Method:       "GET",
			Path:         "/api/auth/callback/{plugin_id}",
			Summary:      "Handle OAuth callback for a plugin",
			Description:  "Consumes the browser redirect callback for OAuth2 or OpenID-style plugin consent flows, invokes auth.oauth.callback on the plugin, publishes oauth_complete or oauth_error over SSE, and returns a small HTML page that closes the tab.",
			ResponseDocs: map[string]string{"200": "HTML callback result page", "500": "Internal server error"},
		},
		{
			Method:      "GET",
			Path:        "/api/events",
			Summary:     "Server-Sent Events stream",
			Description: "Opens a long-lived text/event-stream connection. Emits scan pipeline events (see server/internal/events/scan_events.md), app notifications (integrations, sync, plugin exit, coarse errors; see server/internal/events/notification_events.md), and save-sync migration lifecycle events (`save_sync_migration_started`, `save_sync_migration_progress`, `save_sync_migration_completed`, `save_sync_migration_failed`). Scan payloads include `job_id` so clients can recover in-progress jobs after reload. Each data line is JSON; map payloads include a ts field (RFC3339) when the publisher includes one.",
			ResponseDocs: map[string]string{
				"200": "text/event-stream; connection stays open until client disconnect or server shutdown",
				"500": "Streaming not supported",
			},
		},
		{
			Method:         "POST",
			Path:           "/api/save-sync/migrations",
			Summary:        "Start a save-sync migration job",
			Description:    "Starts a background save migration from one save-sync integration to another. Supports `scope=all` or `scope=game`; `game` requires `canonical_game_id`. Progress and completion arrive over SSE and can also be polled by job id.",
			RequestBodyDoc: "JSON: { source_integration_id, target_integration_id, scope: \"all\"|\"game\", canonical_game_id?, delete_source_after_success? }",
			ResponseDocs:   map[string]string{"202": "SaveSyncMigrationStatus JSON", "400": "Invalid request body or unsupported scope", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/save-sync/migrations/{job_id}",
			Summary:      "Get save-sync migration job status",
			Description:  "Returns the latest in-memory status for a save-sync migration job, including counts for total, completed, migrated, skipped, and any terminal error.",
			ResponseDocs: map[string]string{"200": "SaveSyncMigrationStatus JSON", "404": "Unknown job id", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/save-sync/prefetch/{job_id}",
			Summary:      "Get save-sync prefetch job status",
			Description:  "Returns the latest in-memory status for a save-sync prefetch job, including progress, cached/missing/failed slot counts, and any terminal error.",
			ResponseDocs: map[string]string{"200": "SaveSyncPrefetchStatus JSON", "404": "Unknown job id", "500": "Internal server error"},
		},
	}
}
