package openapi

// OperationDoc holds documentation for one API operation (method + path).
// Used by the generator to fill summary, description, and response codes in the OpenAPI spec.
type OperationDoc struct {
	Method      string // GET, POST, etc.
	Path        string // e.g. /api/games (path params as {id})
	Summary     string // Short one-line summary for the operation.
	Description string // Longer description; optional.
	// RequestBodyDoc describes the request body for POST/PUT/PATCH. Empty means no body or optional.
	RequestBodyDoc string
	// ResponseDocs keyed by status code ("200", "202", "400", "404", "500"). Description for that response.
	ResponseDocs map[string]string
}

// Operations returns documentation for all public API operations.
// Paths must match the routes registered in http.BuildRouter (use {id} for path params).
func Operations() []OperationDoc {
	return []OperationDoc{
		{
			Method:       "GET",
			Path:         "/health",
			Summary:      "Health check",
			Description:  "Returns 200 OK if the server is running. No body.",
			ResponseDocs: map[string]string{"200": "Server is healthy"},
		},
		{
			Method:      "GET",
			Path:        "/api/games",
			Summary:     "List games (paginated)",
			Description: "Returns total, page, page_size and games[] as full detail objects (same shape as GET /api/games/{id}/detail). Query: page (0-based, default 0), page_size (default 100, max 2000), sort_by (title, release_date, platform, rating), and sort_dir (asc, desc). Sorting is applied before pagination. page_size=0 requests all games in one response (rejected if library exceeds 20000 games; use pagination). Totals also available via GET /api/stats (canonical_game_count).",
			ResponseDocs: map[string]string{
				"200": "ListGamesResponse: total, page, page_size, games (GameDetailResponse[])",
				"400": "Invalid query or library too large for page_size=0",
				"500": "Internal server error",
			},
		},
		{
			Method:      "GET",
			Path:        "/api/catalog/offers",
			Summary:     "List catalog offers",
			Description: "Returns this profile's provider offers with the latest append-only availability observation, current/latest package versions, evidence timestamps, entitlement, delivery mode, and staleness. Optional query parameters: canonical_game_id, provider, availability, stale.",
			ResponseDocs: map[string]string{
				"200": "JSON object with profile-scoped offers[]",
				"400": "Invalid availability or stale filter",
				"403": "Profile context is missing or forbidden",
				"500": "Internal server error",
			},
		},
		{
			Method:       "GET",
			Path:         "/api/runtime-artifacts",
			Summary:      "List runtime and emulator artifacts",
			Description:  "Returns the authenticated profile a server-global registry of runtime/emulator package metadata, license, acquisition, compliance, integrity, compatibility and storage evidence. Server filesystem paths are never returned.",
			ResponseDocs: map[string]string{"200": "JSON object with artifacts[]", "401": "Authentication required", "403": "Profile access forbidden", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/runtime-artifacts/{artifact_id}",
			Summary:      "Get a runtime or emulator artifact",
			Description:  "Returns one artifact's compliance and provenance metadata under authenticated selected-profile context.",
			ResponseDocs: map[string]string{"200": "Runtime artifact metadata", "404": "Artifact not found", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/runtime-artifacts",
			Summary:        "Create a runtime or emulator artifact",
			Description:    "Administrator-only complete artifact registration. Unknown license, prohibited category, non-HTTPS source, invalid integrity evidence or inconsistent delivery policy fails closed.",
			RequestBodyDoc: "Complete runtime artifact JSON object",
			ResponseDocs:   map[string]string{"201": "Created artifact", "400": "Invalid artifact policy or evidence", "403": "Administrator required", "500": "Internal server error"},
		},
		{
			Method:         "PUT",
			Path:           "/api/runtime-artifacts/{artifact_id}",
			Summary:        "Update a runtime or emulator artifact",
			Description:    "Administrator-only full replacement. Artifact identity must match the path; blocking compliance preserves the row and prevents bytes.",
			RequestBodyDoc: "Complete runtime artifact JSON object",
			ResponseDocs:   map[string]string{"200": "Updated artifact", "400": "Invalid artifact policy, evidence or identity", "403": "Administrator required", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/runtime-artifacts/{artifact_id}/content",
			Summary:      "Download an approved runtime artifact",
			Description:  "Authenticates the selected profile, revalidates compliance and redistributability, derives a content-addressed path, verifies length and SHA-256, then serves one optional byte range with safe headers.",
			ResponseDocs: map[string]string{"200": "Complete verified artifact bytes", "206": "Requested byte range", "304": "Artifact ETag unchanged", "404": "Artifact not found", "409": "Delivery blocked or integrity failed", "416": "Invalid or multiple range", "500": "Internal server error"},
		},
		{
			Method:       "HEAD",
			Path:         "/api/runtime-artifacts/{artifact_id}/content",
			Summary:      "Inspect an approved runtime artifact",
			Description:  "Performs the same authorization, compliance and integrity checks as GET and returns delivery headers without bytes.",
			ResponseDocs: map[string]string{"200": "Verified artifact headers", "404": "Artifact not found", "409": "Delivery blocked or integrity failed"},
		},
		{
			Method:      "GET",
			Path:        "/api/content/v1/copies/{copy_id}/manifest",
			Summary:     "Get a content-copy manifest",
			Description: "Returns Content Delivery API v1 metadata for one concrete copy owned by the authenticated profile. File IDs are stable opaque hashes; relative paths are validated and no server/source/cache path or credential is exposed.",
			ResponseDocs: map[string]string{
				"200": "Content manifest schema v1",
				"304": "Manifest ETag is unchanged",
				"400": "Invalid copy identifier",
				"404": "Copy missing or owned by another profile",
				"409": "Source file evidence is invalid",
				"500": "Internal server error",
			},
		},
		{
			Method:      "GET",
			Path:        "/api/content/v1/copies/{copy_id}/files/{file_id}",
			Summary:     "Download one content-copy file",
			Description: "Streams one manifest-listed file after revalidating profile, copy, integration, and opaque file ownership. Supports one HTTP byte range, ETag conditional requests, safe attachment naming, explicit MIME, and resumable delivery.",
			ResponseDocs: map[string]string{
				"200": "Complete file bytes",
				"206": "Requested byte range",
				"304": "File ETag is unchanged",
				"400": "Invalid copy or file identifier",
				"404": "Copy/file missing or owned by another profile",
				"409": "Materialization required, delivery unavailable, or source changed",
				"416": "Invalid or multiple byte ranges",
				"429": "Per-profile concurrent stream limit reached",
				"500": "Internal server error",
			},
		},
		{
			Method:      "HEAD",
			Path:        "/api/content/v1/copies/{copy_id}/files/{file_id}",
			Summary:     "Inspect one content-copy file",
			Description: "Returns the same authorization, ETag, MIME, length, range, and content-disposition headers as GET without a response body.",
			ResponseDocs: map[string]string{
				"200": "File headers",
				"404": "Copy/file missing or owned by another profile",
				"409": "Materialization required, delivery unavailable, or source changed",
				"429": "Per-profile concurrent stream limit reached",
			},
		},
		{
			Method:         "POST",
			Path:           "/api/content/v1/copies/{copy_id}/materializations",
			Summary:        "Prepare remote content for delivery",
			Description:    "Starts or reuses a bounded, profile-authorized source-cache job for the current copy evidence. Direct sources complete immediately; remote sources return a durable job that can be polled or cancelled.",
			RequestBodyDoc: "No request body",
			ResponseDocs: map[string]string{
				"200": "Direct source or matching cache is already ready",
				"202": "Materialization job accepted",
				"404": "Copy missing or owned by another profile",
				"409": "Source is not materializable or its manifest is invalid",
				"500": "Internal server error",
			},
		},
		{
			Method:      "GET",
			Path:        "/api/content/v1/materializations/{job_id}",
			Summary:     "Get a content materialization job",
			Description: "Returns sanitized progress for one durable materialization job visible to the authenticated profile. Provider errors, paths, credentials, and foreign-profile facts are never returned.",
			ResponseDocs: map[string]string{
				"200": "Sanitized materialization job",
				"404": "Job missing or owned by another profile",
				"500": "Internal server error",
			},
		},
		{
			Method:         "POST",
			Path:           "/api/content/v1/materializations/{job_id}/cancel",
			Summary:        "Cancel a content materialization job",
			Description:    "Requests cancellation of an active profile-owned materialization. Plugin work receives context cancellation, partial files are removed, and the durable job becomes cancelled.",
			RequestBodyDoc: "No request body",
			ResponseDocs: map[string]string{
				"202": "Cancellation requested",
				"404": "Job missing or owned by another profile",
				"409": "Job is already terminal",
				"500": "Internal server error",
			},
		},
		{
			Method:      "GET",
			Path:        "/api/catalog/offers/{offer_id}",
			Summary:     "Get a catalog offer",
			Description: "Returns one offer only when it belongs to the active profile. Foreign-profile and unknown identifiers both fail closed as not found.",
			ResponseDocs: map[string]string{
				"200": "Catalog Offer JSON",
				"403": "Profile context is missing or forbidden",
				"404": "Offer not found in the active profile",
				"500": "Internal server error",
			},
		},
		{
			Method:      "GET",
			Path:        "/api/catalog/offers/{offer_id}/history",
			Summary:     "List catalog offer history",
			Description: "Returns append-only added, removed, returned, leaving-soon, and version-change events for one active-profile offer, newest first. Optional limit is 1 through 1000 and defaults to 100.",
			ResponseDocs: map[string]string{
				"200": "JSON object with newest-first events[]",
				"400": "Invalid limit",
				"403": "Profile context is missing or forbidden",
				"404": "Offer not found in the active profile",
				"500": "Internal server error",
			},
		},
		{
			Method:       "DELETE",
			Path:         "/api/games",
			Summary:      "Delete all games",
			Description:  "Removes all games and their files from the database. Use before a full rescan to start fresh.",
			ResponseDocs: map[string]string{"200": "All games deleted", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/{id}",
			Summary:      "Get game by ID",
			Description:  "Returns full game detail (same JSON as GET /api/games/{id}/detail and each element of GET /api/games).",
			ResponseDocs: map[string]string{"200": "GameDetailResponse", "404": "Game not found", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/{id}/detail",
			Summary:      "Get game detail",
			Description:  "Full metadata, media (with local_path/hash when known), external IDs, merged files, unified Xbox/xCloud fields (is_game_pass, xcloud_available, store_product_id, xcloud_url when present), Steam Families sharing fields (shared, shared_owner when a title is borrowed), and all source games with resolver_matches. Source records also include generic delivery metadata per profile (`delivery.profiles`) so clients can decide whether a source is direct, materialized, or unavailable. Legacy browser-play fields remain as a compatibility shim.",
			ResponseDocs: map[string]string{"200": "Game detail object", "404": "Game not found", "500": "Internal server error"},
		},
		{
			Method:         "PUT",
			Path:           "/api/games/{id}/cover-override",
			Summary:        "Set game cover override",
			Description:    "Pins one existing media asset that is already linked to the canonical game as the preferred cover. The server rejects media assets that are not linked to the requested game.",
			RequestBodyDoc: "JSON: { media_asset_id: number }",
			ResponseDocs:   map[string]string{"200": "Updated GameDetailResponse", "400": "Invalid request body or media_asset_id", "404": "Game not found", "422": "Media asset is not linked to this game", "500": "Internal server error"},
		},
		{
			Method:       "DELETE",
			Path:         "/api/games/{id}/cover-override",
			Summary:      "Clear game cover override",
			Description:  "Removes a pinned cover override for the canonical game and returns the updated game detail using normal cover selection again.",
			ResponseDocs: map[string]string{"200": "Updated GameDetailResponse", "404": "Game not found", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/games/{id}/refresh-metadata",
			Summary:      "Refresh metadata for one canonical game",
			Description:  "Runs the strict metadata/media refresh flow for one canonical game. Provider failures abort the refresh and return a fast-fail error instead of partial persistence.",
			ResponseDocs: map[string]string{"200": "Updated GameDetailResponse", "404": "Game not found", "409": "No eligible source records remain for refresh", "422": "Metadata providers unavailable or refresh failed fast", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/games/{id}/sources/{source_game_id}/delete-preview",
			Summary:      "Preview hard delete for one source record",
			Description:  "Calls the file-backed source plugin in dry-run mode with the real delete arguments and returns the plugin-resolved file deletion plan without deleting files or database rows.",
			ResponseDocs: map[string]string{"200": "DeleteSourceGamePreview JSON", "404": "Game or source record not found", "409": "Source record is not eligible for hard delete", "500": "Internal server error"},
		},
		{
			Method:       "DELETE",
			Path:         "/api/games/{id}/sources/{source_game_id}",
			Summary:      "Hard delete one source record",
			Description:  "Deletes exactly one eligible file-backed source record, including provider-backed files and dependent database rows, then recomputes canonical grouping. The action never deletes sibling source records implicitly.",
			ResponseDocs: map[string]string{"200": "DeleteSourceGameResponse", "404": "Game or source record not found", "409": "Source record is not eligible for hard delete", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/games/{id}/sources/{source_game_id}/canonical/split",
			Summary:      "Split one source record into its own canonical game",
			Description:  "Pins one visible source record to a newly created canonical game and excludes it from automatic title/external-id grouping during future recomputes.",
			ResponseDocs: map[string]string{"200": "CanonicalGroupingResponse", "404": "Game or source record not found", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/{id}/games/{game_id}/installation-preflight",
			Summary:        "Check a device before installing",
			Description:    "Dispatches a typed read-only MGA Client check for the exact game source, destination template, package size, and prerequisite policy. The endpoint may be any paired LAN device/OS user and plain trusted-LAN HTTP remains supported.",
			RequestBodyDoc: "JSON: { source_game_id: string, install_kind: managed_archive | gog_inno, destination_root?: string }",
			ResponseDocs:   map[string]string{"202": "DeviceCommand JSON; terminal result is InstallationPreflightResult", "400": "Invalid request or unsupported package", "404": "Device, game, or source not found", "409": "Device unavailable or preflight unsupported", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/games/{id}/sources/{source_game_id}/canonical/merge",
			Summary:        "Merge one source record into an existing canonical game",
			Description:    "Pins one visible source record into the selected visible canonical game and excludes it from automatic grouping that would move it elsewhere.",
			RequestBodyDoc: "JSON: { target_canonical_game_id: string }",
			ResponseDocs:   map[string]string{"200": "CanonicalGroupingResponse", "400": "Invalid request body", "404": "Game, source record, or target canonical game not found", "500": "Internal server error"},
		},
		{
			Method:       "DELETE",
			Path:         "/api/games/{id}/sources/{source_game_id}/canonical-pin",
			Summary:      "Clear one source record canonical grouping pin",
			Description:  "Removes a manual split/merge pin for one source record and recomputes canonical grouping using automatic resolver/title rules.",
			ResponseDocs: map[string]string{"200": "CanonicalGroupingResponse", "404": "Game, source record, or pin not found", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/canonical-games/search",
			Summary:      "Search canonical games for merge targets",
			Description:  "Returns visible canonical games matching query parameter q, capped by limit, for source-record merge target selection.",
			ResponseDocs: map[string]string{"200": "CanonicalGameSearchResponse", "400": "Invalid limit", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/games/sources/delete-batch",
			Summary:      "Hard delete multiple source records",
			Description:  "Deletes explicitly selected eligible file-backed source records as one operation. Provider file delete plans are built before execution, duplicate backing file operations are skipped, and canonical grouping is recomputed once after database rows are removed.",
			ResponseDocs: map[string]string{"200": "DeleteSourceGamesResponse", "400": "Invalid request", "404": "Game or source record not found", "409": "Source record is not eligible for hard delete", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/games/sources/move-preview",
			Summary:        "Preview safe game-file moves",
			Description:    "Builds a non-mutating, profile-scoped move plan with exact files, destination storage identity, source cleanup behavior, and whole-folder safety evidence.",
			RequestBodyDoc: "JSON: { items: [{ canonical_game_id, source_game_id, destination_integration_id, destination_path }] }",
			ResponseDocs:   map[string]string{"200": "SourceMovePreview JSON", "400": "Invalid, unsafe, unsupported, or cross-profile request", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/games/sources/moves",
			Summary:        "Start recoverable game-file moves",
			Description:    "Persists and starts verified copy-before-delete moves. Each destination is reserved across profiles by backing storage identity and path until the job reaches a finished state.",
			RequestBodyDoc: "JSON: { items: [{ canonical_game_id, source_game_id, destination_integration_id, destination_path }] }",
			ResponseDocs:   map[string]string{"202": "JSON object with jobs[] of SourceMoveJob", "400": "Invalid request", "409": "Destination collision or move cannot start", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/source-move-destinations",
			Summary:      "List safe move destinations",
			Description:  "Lists this profile's enabled game-source connections that implement the complete destination transfer protocol. Connection secrets and backing storage identities are not returned.",
			ResponseDocs: map[string]string{"200": "JSON object with destinations[] of SourceMoveDestination", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/source-moves",
			Summary:      "List recoverable game-file moves",
			Description:  "Returns this profile's persisted move history and any active or actionable recovery jobs. Query: limit (optional, defaults to 50).",
			ResponseDocs: map[string]string{"200": "JSON object with jobs[] of SourceMoveJob", "400": "Invalid limit", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/source-moves/{job_id}",
			Summary:      "Get one game-file move",
			Description:  "Returns one move job only when it belongs to the active profile.",
			ResponseDocs: map[string]string{"200": "SourceMoveJob JSON", "404": "Move job not found", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/games/source-moves/{job_id}/retry",
			Summary:      "Retry a recoverable game-file move",
			Description:  "Retries from the persisted safe boundary. Before commit, MGA removes only its owned stage and recopies; after commit, it retries library discovery or original cleanup without replacing the verified destination.",
			ResponseDocs: map[string]string{"202": "Updated SourceMoveJob JSON", "404": "Move job not found", "409": "Move is not retryable or recovery failed", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/games/source-moves/{job_id}/cleanup",
			Summary:      "Clean an uncommitted move stage",
			Description:  "Removes only MGA-owned temporary destination content for a pre-commit failed or interrupted move. The original remains unchanged.",
			ResponseDocs: map[string]string{"202": "Updated SourceMoveJob JSON", "404": "Move job not found", "409": "Move is not eligible for stage cleanup", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/games/source-moves/{job_id}/keep-both",
			Summary:      "Finish a move by keeping both copies",
			Description:  "Keeps the verified destination and original after a post-commit recovery condition, then refreshes the library and completes the job.",
			ResponseDocs: map[string]string{"202": "Updated SourceMoveJob JSON", "404": "Move job not found", "409": "Move is not eligible to keep both", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/{id}/play",
			Summary:      "Stream one game file by file_id",
			Description:  "Streams a single file that belongs to the requested canonical game. Requires query param file_id (stable id from game detail/list file metadata). Direct local sources stream immediately; materialized sources such as SMB/Drive require `profile` so the server can open the prepared cached file. Supports GET, HEAD, and Range requests via http.ServeContent.",
			ResponseDocs: map[string]string{"200": "Binary stream", "400": "Missing or invalid file_id", "404": "Game, file, source path, or prepared cache file not found", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/games/{id}/cache/prepare",
			Summary:        "Prepare cached source files for one delivery profile",
			Description:    "Starts or reuses a cache/materialization job for one source record and delivery profile. Direct sources may return an immediate completed response; remote materializable sources return 202 while the job downloads into the reusable source cache.",
			RequestBodyDoc: "JSON: { source_game_id: string, profile: string }",
			ResponseDocs:   map[string]string{"200": "CachePrepareResponse JSON; source already ready or direct", "202": "CachePrepareResponse JSON; job accepted", "400": "Invalid game id, source_game_id, or profile", "404": "Game not found", "503": "Cache service unavailable"},
		},
		{
			Method:       "GET",
			Path:         "/api/cache/jobs",
			Summary:      "List recent cache prepare jobs",
			Description:  "Returns recent cache prepare/materialization jobs in reverse-updated order. Query: limit (optional, defaults to 25).",
			ResponseDocs: map[string]string{"200": "JSON object with jobs[] of SourceCacheJobStatus", "500": "Internal server error", "503": "Cache service unavailable"},
		},
		{
			Method:       "GET",
			Path:         "/api/cache/jobs/{job_id}",
			Summary:      "Get one cache prepare job",
			Description:  "Returns persisted status for one cache prepare/materialization job, including progress, terminal error, and entry linkage when ready.",
			ResponseDocs: map[string]string{"200": "SourceCacheJobStatus JSON", "400": "job_id is required", "404": "Job not found", "500": "Internal server error", "503": "Cache service unavailable"},
		},
		{
			Method:       "GET",
			Path:         "/api/cache/entries",
			Summary:      "List cached source entries",
			Description:  "Returns all reusable cache entries with operator-facing metadata such as integration label, source context, profile, status, size, and timestamps.",
			ResponseDocs: map[string]string{"200": "JSON object with entries[] of cache entry DTOs", "500": "Internal server error", "503": "Cache service unavailable"},
		},
		{
			Method:       "GET",
			Path:         "/api/duplicates/games",
			Summary:      "List duplicate game source records",
			Description:  "Returns duplicate-looking source record groups for Settings cleanup. Query mode=loose groups normalized titles across sources and platforms; mode=strict groups same-title variants inside an existing canonical game. Source records include hard-delete eligibility so the client can reuse the source delete preview/delete flow.",
			ResponseDocs: map[string]string{"200": "DuplicateGamesResponse JSON", "400": "Invalid mode", "500": "Internal server error"},
		},
		{
			Method:       "DELETE",
			Path:         "/api/cache/entries/{entry_id}",
			Summary:      "Evict one cached source entry",
			Description:  "Deletes one cache entry, its tracked files, and the materialized files on disk.",
			ResponseDocs: map[string]string{"204": "Entry deleted", "400": "entry_id is required", "500": "Internal server error", "503": "Cache service unavailable"},
		},
		{
			Method:       "POST",
			Path:         "/api/cache/clear",
			Summary:      "Clear all cached source entries",
			Description:  "Deletes all reusable cache entries and removes the materialized cache root contents.",
			ResponseDocs: map[string]string{"200": "Status ok JSON", "500": "Internal server error", "503": "Cache service unavailable"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/{id}/save-sync/slots",
			Summary:      "List save-sync slots for one browser runtime source",
			Description:  "Returns local cached summary metadata for save-sync slots for the requested canonical game, source game, runtime, and save-sync integration. Query params: integration_id, source_game_id, runtime.",
			ResponseDocs: map[string]string{"200": "JSON object with slots[] of SaveSyncSlotSummary", "400": "Missing or invalid integration_id, source_game_id, or runtime", "404": "Game not found", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/games/{id}/save-sync/prefetch",
			Summary:        "Prefetch save-sync slots into the local cache",
			Description:    "Starts a background prefetch of EmulatorJS save-sync slots from the active remote integration into the server local cache. Missing remote slots are cached as empty; provider failures fail the job.",
			RequestBodyDoc: "JSON: { integration_id, source_game_id, runtime }",
			ResponseDocs:   map[string]string{"202": "SaveSyncPrefetchStatus JSON", "400": "Invalid parameters", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/{id}/save-sync/slots/{slot_id}",
			Summary:      "Get one cached save-sync slot snapshot",
			Description:  "Loads the manifest metadata and opaque zip snapshot for one browser-runtime save slot from the server local cache. Query params: integration_id, source_game_id, runtime.",
			ResponseDocs: map[string]string{"200": "SaveSyncSnapshot JSON", "400": "Missing or invalid parameters", "404": "Slot or game not found", "500": "Internal server error"},
		},
		{
			Method:         "PUT",
			Path:           "/api/games/{id}/save-sync/slots/{slot_id}",
			Summary:        "Store one save-sync slot snapshot",
			Description:    "Stores a whole runtime save snapshot into the local server cache and queues a cloud upload. The server validates ownership, runtime compatibility, file manifest integrity, and optional conflict state via `base_manifest_hash`. Use `force=true` to overwrite after a conflict warning.",
			RequestBodyDoc: "JSON: { integration_id, source_game_id, runtime, base_manifest_hash?, force?, snapshot: { canonical_game_id?, source_game_id?, runtime?, slot_id?, files[], archive_base64 } }",
			ResponseDocs:   map[string]string{"200": "SaveSyncPutResult JSON", "400": "Invalid parameters or snapshot payload", "404": "Game or slot target not found", "409": "SaveSyncPutResult with conflict metadata", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/media/{assetID}",
			Summary:      "Stream cached media file",
			Description:  "Serves a file from MEDIA_ROOT using media_assets.id and the row's local_path (must be relative, no '..'). Set MEDIA_ROOT in config (default ./media). Use media[].asset_id from game detail. Supports Range, HEAD and conditional requests via http.ServeContent: the ETag is the stored SHA-256 of the downloaded bytes, or a weak size-and-mtime validator for rows with no recorded checksum. Cached as private, not public, because the asset is only served to an authorized profile.",
			ResponseDocs: map[string]string{"200": "Binary stream", "206": "Partial content for a Range request", "304": "Not modified; the client's validator still matches", "307": "Local file is missing; redirected to the original http(s) URL while MGA requeues the download", "400": "Invalid id", "404": "Unknown asset or missing file with no safe original URL", "500": "Internal server error"},
		},
		{
			Method:         "PUT",
			Path:           "/api/media/{assetID}/metadata",
			Summary:        "Backfill media dimensions",
			Description:    "Stores probed width/height metadata for an existing media asset so future clients can make layout decisions without probing again.",
			RequestBodyDoc: "JSON: { width: number, height: number, mime_type?: string }",
			ResponseDocs:   map[string]string{"204": "Metadata updated", "400": "Invalid id or body", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/media/queue/status",
			Summary:      "Get media download queue status",
			Description:  "Returns DB-backed media download counts plus in-memory queued and downloading counts for the asynchronous media cache.",
			ResponseDocs: map[string]string{"200": "MediaDownloadStatus JSON", "403": "Admin profile required", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/media/queue/retry-failed",
			Summary:      "Retry failed media downloads",
			Description:  "Clears retryable media download failures and enqueues pending media downloads in the background. Permanent failures remain untouched.",
			ResponseDocs: map[string]string{"200": "MediaDownloadStatus JSON", "403": "Admin profile required", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/media/cache/clear",
			Summary:      "Clear downloaded media cache",
			Description:  "Deletes local downloaded artwork/video files under MEDIA_ROOT, clears media local_path/hash and failure state, keeps media rows and library metadata, then enqueues media downloads again.",
			ResponseDocs: map[string]string{"200": "MediaDownloadStatus JSON", "403": "Admin profile required", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/stats",
			Summary:      "Library statistics",
			Description:  "Single JSON document: canonical and source game counts, breakdowns by platform/kind/integration/plugin, metadata coverage, decade and genre summaries, and canonical-game coverage for media and achievements.",
			ResponseDocs: map[string]string{"200": "LibraryStats JSON", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/stats/library",
			Summary:      "Richer library statistics",
			Description:  "Read-only library dashboard aggregates: compatible LibraryStats summary plus ranked platform, source, integration, metadata provider, decade, genre, coverage, and recent scan activity sections.",
			ResponseDocs: map[string]string{"200": "LibraryStatistics JSON", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/stats/gamer",
			Summary:      "Gamer statistics",
			Description:  "Read-only player-facing aggregates from existing data: favorites, stored achievement totals, achievement systems, and completion buckets. Does not persist play-history events.",
			ResponseDocs: map[string]string{"200": "GamerStatistics JSON", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/about",
			Summary:      "Application build metadata",
			Description:  "Returns the server's authoritative app version information, including version, commit, build date, and author credits.",
			ResponseDocs: map[string]string{"200": "AboutInfo JSON", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/about/license",
			Summary:      "Open-source license text",
			Description:  "Streams the repository license file used by the About page.",
			ResponseDocs: map[string]string{"200": "License text", "500": "License file not found"},
		},
		{
			Method:       "GET",
			Path:         "/api/games/{id}/achievements",
			Summary:      "Get achievements for a game",
			Description:  "Fetches achievements on-demand from all achievement-capable plugins that have an external ID match for this game. Returns an array of achievement sets, one per source (steam, xbox, retroachievements).",
			ResponseDocs: map[string]string{"200": "Array of achievement sets", "400": "id required", "404": "Game not found", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/achievements",
			Summary:      "Get stored achievements dashboard",
			Description:  "Returns stored achievement totals by system and by canonical game plus the latest achievement refresh state. This endpoint only reads server-owned SQLite rows and does not fetch achievements from external integrations.",
			ResponseDocs: map[string]string{"200": "AchievementsDashboardResponse", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/achievements/explorer",
			Summary:      "Get stored achievements explorer",
			Description:  "Returns stored achievement sets and achievement rows grouped by canonical game. This endpoint is read-only over server-owned SQLite rows and does not trigger provider fetches.",
			ResponseDocs: map[string]string{"200": "AchievementsExplorerResponse", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/achievements/refresh",
			Summary:      "Start achievements refresh",
			Description:  "Starts a background job that refreshes achievements for all profile-visible games with configured achievement-capable integrations. Provider calls are throttled and may emit waiting/progress events when a provider rate-limits refresh work. Provider failures are persisted as degraded per-game state and do not stop unrelated games.",
			ResponseDocs: map[string]string{"202": "AchievementRefreshJobStatus", "409": "An achievement refresh job is already active", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/achievements/refresh/jobs/{job_id}",
			Summary:      "Get achievements refresh job",
			Description:  "Returns the latest in-memory status for an achievement refresh job, including current provider, item, and optional provider backoff wait state.",
			ResponseDocs: map[string]string{"200": "AchievementRefreshJobStatus", "404": "Job not found"},
		},
		{
			Method:         "POST",
			Path:           "/api/scan",
			Summary:        "Run scan",
			Description:    "Starts an asynchronous scan job. Runs discovery: calls each source plugin (source.library.list) and, for integrations with root_path in config, runs the local inventory pipeline. Optional body limits which sources to scan or requests metadata-only refresh.",
			RequestBodyDoc: "Optional JSON: { \"game_sources\": [\"integration-id-1\", ...], \"metadata_only\": true|false }. Omitted or empty game_sources = scan all sources.",
			ResponseDocs: map[string]string{
				"202": "ScanJobStatus JSON",
				"400": "Invalid JSON body",
				"409": "Another scan job is already active; returns the active ScanJobStatus",
				"500": "Internal server error",
			},
		},
		{
			Method:      "GET",
			Path:        "/api/scan",
			Summary:     "Run full scan",
			Description: "Same as POST /api/scan with no body: starts an asynchronous full-library scan job across all game source integrations.",
			ResponseDocs: map[string]string{
				"202": "ScanJobStatus JSON",
				"409": "Another scan job is already active; returns the active ScanJobStatus",
				"500": "Internal server error",
			},
		},
		{
			Method:       "GET",
			Path:         "/api/scan/jobs/{job_id}",
			Summary:      "Get scan job status",
			Description:  "Returns the current in-memory status for an asynchronous scan job, including state, integration-level progress snapshots, a rolling recent-events log, current integration, report id, and any terminal error.",
			ResponseDocs: map[string]string{"200": "ScanJobStatus JSON", "400": "job_id is required", "404": "Unknown job id", "500": "Internal server error"},
		},
		{
			Method:      "POST",
			Path:        "/api/scan/jobs/{job_id}/cancel",
			Summary:     "Cancel a running scan job",
			Description: "Requests cancellation for an asynchronous scan job. Returns the updated ScanJobStatus. Jobs transition through cancelling and then cancelled if the worker exits due to context cancellation.",
			ResponseDocs: map[string]string{
				"200": "ScanJobStatus JSON; job was already cancelling or cancelled",
				"202": "ScanJobStatus JSON; cancellation requested",
				"400": "job_id is required",
				"404": "Unknown job id",
				"409": "ScanJobStatus JSON; job is already completed or failed",
				"500": "Internal server error",
			},
		},
		{
			Method:      "GET",
			Path:        "/api/scan/background",
			Summary:     "Get automatic library scan status",
			Description: "Returns the active profile's automatic scan schedule, next run, latest outcome, and active background job when one is running.",
			ResponseDocs: map[string]string{
				"200": "LibraryScanScheduleStatus JSON",
				"500": "Internal server error",
				"503": "Background scanning is unavailable",
			},
		},
		{
			Method:      "PUT",
			Path:        "/api/scan/background",
			Summary:     "Configure automatic library scans",
			Description: "Enables or disables profile-scoped automatic source scans and sets their interval in minutes. Automatic and manual scans use the same scan job coordinator and reconciliation pipeline.",
			ResponseDocs: map[string]string{
				"200": "Updated LibraryScanScheduleStatus JSON",
				"400": "Invalid JSON or interval",
				"503": "Background scanning is unavailable",
			},
		},
		{
			Method:      "GET",
			Path:        "/api/scan/reports",
			Summary:     "List recent scan reports",
			Description: "Returns the most recent persisted scan reports in reverse chronological order. Query: limit (optional, defaults to 10). Each report includes totals plus per-integration diff summaries.",
			ResponseDocs: map[string]string{
				"200": "Array of ScanReport JSON objects",
				"500": "Internal server error",
			},
		},
		{
			Method:       "GET",
			Path:         "/api/scan/reports/{id}",
			Summary:      "Get one scan report",
			Description:  "Returns one persisted scan report by id, including totals, timing, metadata_only flag, and per-integration results.",
			ResponseDocs: map[string]string{"200": "ScanReport JSON", "400": "id is required", "404": "Report not found", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/plugins",
			Summary:      "List plugins",
			Description:  "Returns the list of discovered plugins with ID, version, and capabilities.",
			ResponseDocs: map[string]string{"200": "Array of plugin descriptors", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/plugins/{plugin_id}",
			Summary:      "Get plugin by ID",
			Description:  "Returns a single plugin's descriptor including config schema.",
			ResponseDocs: map[string]string{"200": "Plugin info", "400": "plugin_id required", "404": "Plugin not found", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/config/frontend",
			Summary:      "Get frontend preferences",
			Description:  "Returns stored SPA preferences as a JSON object; {} if unset or invalid.",
			ResponseDocs: map[string]string{"200": "JSON object", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/config/frontend",
			Summary:        "Set frontend preferences",
			Description:    "Upserts SPA preferences as a single JSON object (theme, layout, active save-sync integration, etc.). Stored under key frontend.",
			RequestBodyDoc: "JSON object (any keys). Max size enforced by server.",
			ResponseDocs:   map[string]string{"200": "Saved", "400": "Not a JSON object or too large", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/config/{key}",
			Summary:        "Set config value",
			Description:    "Upserts a configuration value by key (e.g. google_drive_creds).",
			RequestBodyDoc: "JSON: { \"value\": \"string\" }",
			ResponseDocs:   map[string]string{"200": "Value set", "400": "Invalid body", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/integrations",
			Summary:      "List integrations",
			Description:  "Returns all configured integrations (plugin instances) with id, plugin_id, label, integration_type, config.",
			ResponseDocs: map[string]string{"200": "Array of integrations", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/integrations/status",
			Summary:      "Integration status",
			Description:  "Returns status for each integration (ok, error, unavailable) by calling plugin.check_config.",
			ResponseDocs: map[string]string{"200": "Array of { integration_id, plugin_id, label, status, message }", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/integrations",
			Summary:        "Create integration",
			Description:    "Creates a new integration (plugin instance). Validates config against plugin schema and plugin.check_config before persisting.",
			RequestBodyDoc: "JSON: { \"plugin_id\": \"string\", \"label\": \"string\", \"integration_type\": \"source\"|\"metadata\"|..., \"config\": {} }",
			ResponseDocs: map[string]string{
				"201": "Integration created (body is the integration)",
				"400": "Validation error (missing/invalid plugin_id, label, integration_type, or config)",
				"409": "duplicate_integration: same plugin_id and equivalent config JSON (body includes integration_id and integration)",
				"500": "Internal server error",
			},
		},
		{
			Method:       "GET",
			Path:         "/api/integrations/{id}/status",
			Summary:      "Validate one integration",
			Description:  "Runs plugin.check_config for one saved integration and returns a single IntegrationStatusEntry with status, label, and message.",
			ResponseDocs: map[string]string{"200": "IntegrationStatusEntry JSON", "400": "id is required", "404": "Integration not found", "500": "Internal server error"},
		},
		{
			Method:      "POST",
			Path:        "/api/integrations/{id}/authorize",
			Summary:     "Start or resume OAuth for one integration",
			Description: "Validates the saved config for one integration and either returns its current status or, when browser consent is still required, returns the same oauth_required payload used by create so the frontend can open the authorization URL.",
			ResponseDocs: map[string]string{
				"200": "IntegrationStatusEntry JSON when no browser auth step is needed",
				"202": "OAuthRequiredResponse JSON with authorize_url and state",
				"400": "Invalid id or saved config",
				"404": "Integration not found",
				"500": "Internal server error",
			},
		},
		{
			Method:      "POST",
			Path:        "/api/auth/qr/{plugin_id}/begin",
			Summary:     "Start an app-approval (QR) sign-in",
			Description: "Asks the plugin to begin a sign-in the player approves in the provider's own mobile app, and returns the challenge URL plus the session identifiers to poll with. No password or second factor is ever entered into MGA.",
			ResponseDocs: map[string]string{
				"200": "Challenge JSON with client_id, request_id, challenge_url, and interval_seconds",
				"400": "plugin_id or profile missing",
				"502": "The provider did not return a usable challenge",
			},
		},
		{
			Method:      "POST",
			Path:        "/api/auth/qr/{plugin_id}/poll",
			Summary:     "Poll an app-approval (QR) sign-in",
			Description: "Reports whether the player has approved the challenge yet. While pending it returns status \"pending\" and may include a replacement challenge_url that the UI must display immediately without changing the session identifiers. Once approved it binds the token-proven provider identity, stores the returned long-lived credential on the calling profile's own connection, and clears any re-authentication flag.",
			ResponseDocs: map[string]string{
				"200": "Poll JSON with status \"pending\" or \"ok\" (plus a rotated challenge_url while pending or safe provider_identity/persona metadata when approved)",
				"400": "Missing session fields, unknown connection, plugin mismatch, another profile's connection, or an expired challenge",
				"500": "Credentials could not be saved",
			},
		},
		{
			Method:       "GET",
			Path:         "/api/integrations/{id}/games",
			Summary:      "List games discovered by one source integration",
			Description:  "Returns lightweight canonical game rows for games linked to the specified source integration. Intended for Settings drill-down lists and quick inspection.",
			ResponseDocs: map[string]string{"200": "Array of GameListItem JSON", "400": "id is required", "404": "Integration not found", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/integrations/{id}/enriched-games",
			Summary:      "List games enriched by one metadata integration",
			Description:  "Resolves the saved integration to its plugin_id and returns lightweight canonical game rows enriched by that metadata provider's plugin.",
			ResponseDocs: map[string]string{"200": "Array of GameListItem JSON", "400": "id is required", "404": "Integration not found", "500": "Internal server error"},
		},
		{
			Method:      "POST",
			Path:        "/api/integrations/{id}/validate-files",
			Summary:     "Validate files for an integration",
			Description: "Asks the owning file-backed source plugin for an authoritative current listing, then compares stable object IDs and source-relative paths with this profile's stored source records. A connection/listing failure never classifies prior content as missing.",
			ResponseDocs: map[string]string{
				"200": "FileValidationReport with connection context, game/file counts, missing game paths, and per-record failures",
				"400": "id is required",
				"404": "Integration not found",
				"409": "Integration does not support file validation",
				"422": "Connection listing or validation failed",
			},
		},
		{
			Method:      "POST",
			Path:        "/api/integrations/{id}/remove-missing-records",
			Summary:     "Remove selected stale library records",
			Description: "Revalidates the selected records through their owning connection, then removes only the stale source records from MGA. This operation never invokes source filesystem deletion and does not delete files or saves.",
			ResponseDocs: map[string]string{
				"200": "RemoveMissingRecordsResult with removed source game IDs and remaining missing count",
				"400": "Invalid request body or id is required",
				"404": "Integration not found",
				"409": "Selection is empty, unsupported, or no longer missing",
				"422": "Connection listing, validation, or database cleanup failed",
			},
		},
		{
			Method:      "GET",
			Path:        "/api/review-candidates",
			Summary:     "List manual-review candidates",
			Description: "Returns manual-review candidate summaries for the Undetected Games workflow. Query: scope (active or archive, default active) and limit (optional). Review state can be pending, matched, or not_a_game.",
			ResponseDocs: map[string]string{
				"200": "Array of ManualReviewCandidateSummary JSON",
				"400": "Invalid scope or limit",
				"500": "Internal server error",
			},
		},
		{
			Method:       "GET",
			Path:         "/api/review-candidates/{id}",
			Summary:      "Get one manual-review candidate",
			Description:  "Returns full manual-review candidate detail including files, resolver matches, current review_state, and linked canonical game id when present.",
			ResponseDocs: map[string]string{"200": "ManualReviewCandidateDetail JSON", "400": "id is required", "404": "Candidate not found", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/review-candidates/redetect",
			Summary:      "Re-detect active manual-review candidates",
			Description:  "Runs the strict automatic metadata re-detect workflow for all active pending manual-review candidates. Provider or workflow errors fail fast and return partial batch counts plus the candidate id that aborted the run.",
			ResponseDocs: map[string]string{"200": "ManualReviewRedetectBatchResult JSON", "500": "Fail-fast batch error with partial ManualReviewRedetectBatchResult JSON"},
		},
		{
			Method:         "POST",
			Path:           "/api/review-candidates/{id}/search",
			Summary:        "Search metadata providers for a review candidate",
			Description:    "Runs a manual search across configured metadata providers for one candidate. If query is omitted, the server derives a best-effort title query from the candidate data.",
			RequestBodyDoc: "Optional JSON: { query?: string }",
			ResponseDocs:   map[string]string{"200": "ManualReviewSearchResponse JSON", "400": "Invalid body or missing id", "404": "Candidate not found", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/review-candidates/{id}/redetect",
			Summary:      "Re-detect one manual-review candidate",
			Description:  "Runs strict automatic metadata identify, consensus, and fill for one pending manual-review candidate. Identified results persist through the normal scan refresh path; unidentified results leave the candidate pending.",
			ResponseDocs: map[string]string{"200": "ManualReviewRedetectResponse JSON", "400": "Missing id or candidate not eligible", "404": "Candidate not found", "500": "Metadata providers unavailable or internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/review-candidates/{id}/apply",
			Summary:        "Apply a manual-review search result",
			Description:    "Persists a chosen manual-review metadata match for the candidate, marks review_state as matched, and updates the candidate detail that the UI should continue showing. Optional metadata enrichment failures do not discard the selected match and are returned as metadata_warnings. Direct game reclassify may send authoritative_reclassify=true to replace stale resolver/media state with only the selected result and clear media overrides.",
			RequestBodyDoc: "JSON manual-review search result object (provider ids, external_id, title, optional metadata fields, optional authoritative_reclassify).",
			ResponseDocs:   map[string]string{"200": "Updated ManualReviewCandidateDetail JSON", "400": "Invalid body or missing id", "404": "Candidate not found", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/review-candidates/{id}/not-a-game",
			Summary:      "Archive a candidate as not a game",
			Description:  "Marks the candidate review_state as not_a_game and moves it out of the active Undetected Games queue while preserving the decision for later scan refreshes.",
			ResponseDocs: map[string]string{"200": "Updated ManualReviewCandidateDetail JSON", "400": "Missing id", "404": "Candidate not found", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/review-candidates/{id}/dlc",
			Summary:      "Archive a candidate as add-on content",
			Description:  "Marks the source record kind as dlc and review_state as not_a_game, moving installer add-ons out of the active Undetected Games queue while keeping the record inspectable in the archive.",
			ResponseDocs: map[string]string{"200": "Updated ManualReviewCandidateDetail JSON", "400": "Missing id", "404": "Candidate not found", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/review-candidates/{id}/base-game",
			Summary:      "Restore an archived add-on candidate as a base game",
			Description:  "Marks the source record kind as base_game and review_state as pending so a manually archived add-on can return to the active Undetected Games queue.",
			ResponseDocs: map[string]string{"200": "Updated ManualReviewCandidateDetail JSON", "400": "Missing id", "404": "Candidate not found", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/review-candidates/{id}/unarchive",
			Summary:      "Restore an archived manual-review candidate",
			Description:  "Moves an archived candidate back into the active queue and resets its review_state to pending so it can be worked again.",
			ResponseDocs: map[string]string{"200": "Updated ManualReviewCandidateDetail JSON", "400": "Missing id", "404": "Candidate not found", "500": "Internal server error"},
		},
		{
			Method:       "POST",
			Path:         "/api/review-candidates/{id}/files/delete-preview",
			Summary:      "Preview delete for a manual-review candidate's backing files",
			Description:  "Calls the file-backed source plugin in dry-run mode with the real candidate file delete arguments and returns the plugin-resolved deletion plan without deleting files or database rows.",
			ResponseDocs: map[string]string{"200": "DeleteSourceGamePreview JSON", "400": "Missing id", "404": "Candidate not found", "409": "Candidate source is not eligible for destructive deletion", "500": "Internal server error"},
		},
		{
			Method:       "DELETE",
			Path:         "/api/review-candidates/{id}/files",
			Summary:      "Delete a manual-review candidate's backing files",
			Description:  "Destructively deletes the filesystem-backed source files for one manual-review candidate, removes the candidate source record, and recomputes canonical membership.",
			ResponseDocs: map[string]string{"200": "ManualReviewDeleteCandidateFilesResponse JSON", "400": "Missing id", "404": "Candidate not found", "409": "Candidate source is not eligible for destructive deletion", "500": "Internal server error"},
		},
		{
			Method:         "PUT",
			Path:           "/api/integrations/{id}",
			Summary:        "Update one integration",
			Description:    "Updates selected integration fields. Label and integration_type are merged when present; config is optional but, when supplied, must remain a JSON object that passes schema validation and plugin.check_config. OAuth-backed plugins may return oauth_required so the frontend can complete consent before retrying the save.",
			RequestBodyDoc: "JSON: { label?, integration_type?, config? }",
			ResponseDocs: map[string]string{
				"200": "Updated integration JSON",
				"202": "OAuthRequiredResponse JSON with authorize_url and state",
				"400": "Invalid id, JSON body, or config",
				"404": "Integration not found",
				"500": "Internal server error",
			},
		},
		{
			Method:       "DELETE",
			Path:         "/api/integrations/{id}",
			Summary:      "Delete one integration",
			Description:  "Deletes the integration. If the plugin has source capability, the server also cascade-deletes associated source games and related child rows before removing the integration.",
			ResponseDocs: map[string]string{"204": "Integration deleted", "400": "id is required", "404": "Integration not found", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/plugins/{plugin_id}/check-config",
			Summary:        "Validate draft plugin config",
			Description:    "Runs schema validation and plugin.check_config for a draft config without creating or updating an integration. OAuth-backed plugins may return oauth_required so the frontend can authenticate before enabling remote browsing.",
			RequestBodyDoc: "JSON: { config: object }",
			ResponseDocs:   map[string]string{"200": "Plugin check result JSON", "202": "OAuthRequiredResponse JSON with authorize_url and state", "400": "Invalid plugin id, JSON body, or config", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/plugins/{plugin_id}/browse",
			Summary:        "Browse source paths via a plugin",
			Description:    "Proxies a source.browse IPC call to a plugin so the frontend can browse remote/local path trees during integration setup.",
			RequestBodyDoc: "JSON: { path: string }",
			ResponseDocs:   map[string]string{"200": "Plugin-defined browse result JSON", "400": "plugin_id required or invalid body", "500": "Browse failed"},
		},
		{
			Method:       "GET",
			Path:         "/api/sync/status",
			Summary:      "Get sync configuration status",
			Description:  "Returns whether settings sync is configured, whether an encrypted key/passphrase is already stored locally, and timestamps for the last push and pull operations when known.",
			ResponseDocs: map[string]string{"200": "SyncStatus JSON", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/sync/push",
			Summary:        "Push settings sync snapshot",
			Description:    "Exports the local sync payload and uploads it through the configured sync integration. Optional passphrase in the body overrides any stored key for this request.",
			RequestBodyDoc: "Optional JSON: { passphrase?: string }",
			ResponseDocs:   map[string]string{"200": "PushResult JSON", "400": "Invalid JSON body", "500": "Sync push failed"},
		},
		{
			Method:         "POST",
			Path:           "/api/sync/pull",
			Summary:        "Pull and merge settings sync snapshot",
			Description:    "Downloads the latest remote sync payload, decrypts it, and merges integrations/settings into the local database. Optional passphrase in the body overrides any stored key for this request.",
			RequestBodyDoc: "Optional JSON: { passphrase?: string }",
			ResponseDocs:   map[string]string{"200": "PullResult JSON", "400": "Invalid JSON body", "500": "Sync pull failed"},
		},
		{
			Method:         "POST",
			Path:           "/api/sync/key",
			Summary:        "Store sync passphrase locally",
			Description:    "Stores the sync passphrase/key for later push/pull operations so the frontend does not need to resend it every time. If a key is already stored and the new passphrase differs, current_passphrase is required and must match the stored key.",
			RequestBodyDoc: "JSON: { passphrase: string, current_passphrase?: string }",
			ResponseDocs:   map[string]string{"200": "Status ok JSON", "400": "Invalid JSON body, missing passphrase, missing current passphrase, or incorrect current passphrase", "500": "Failed to store sync key"},
		},
		{
			Method:       "DELETE",
			Path:         "/api/sync/key",
			Summary:      "Clear stored sync passphrase",
			Description:  "Deletes the locally stored sync key/passphrase without changing remote data.",
			ResponseDocs: map[string]string{"200": "Status ok JSON", "500": "Failed to clear sync key"},
		},
		{
			Method:         "POST",
			Path:           "/api/auth/callback/import",
			Summary:        "Import pasted OAuth callback URL",
			Description:    "Completes an OAuth2 or OpenID-style plugin consent flow when the provider callback cannot reach MGA automatically. The client posts the final callback URL copied from the browser address bar; MGA validates the callback path, plugin id, and pending state, then invokes the same auth.oauth.callback plugin method used by direct redirects.",
			RequestBodyDoc: "JSON: { plugin_id: string, callback_url: string }",
			ResponseDocs:   map[string]string{"200": "Status ok JSON", "400": "Malformed URL, wrong callback path/plugin, missing or stale state, provider denial, or plugin callback failure", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/auth/callback/{plugin_id}",
			Summary:      "Handle OAuth callback for a plugin",
			Description:  "Consumes the browser redirect callback for OAuth2 or OpenID-style plugin consent flows, invokes auth.oauth.callback on the plugin, publishes oauth_complete or oauth_error over SSE, and returns a small HTML page that closes the tab.",
			ResponseDocs: map[string]string{"200": "HTML callback result page", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/auth/google/callback/{plugin_id}",
			Summary:      "Handle Google OAuth callback for a Drive plugin",
			Description:  "Compatibility callback path registered with the MGA Google OAuth client. It behaves like /api/auth/callback/{plugin_id}, invokes auth.oauth.callback on the plugin, publishes oauth_complete or oauth_error over SSE, and returns a small HTML page that closes the tab.",
			ResponseDocs: map[string]string{"200": "HTML callback result page", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/auth/xbox/callback",
			Summary:      "Handle Xbox OAuth callback",
			Description:  "Compatibility callback path registered with the MGA Microsoft/Xbox OAuth client. Xbox's generated authorize URL uses /api/auth/callback/game-source-xbox; keep this route available because it is also registered with Microsoft.",
			ResponseDocs: map[string]string{"200": "HTML callback result page", "500": "Internal server error"},
		},
		{
			Method:      "GET",
			Path:        "/api/events",
			Summary:     "Server-Sent Events stream",
			Description: "Opens a long-lived text/event-stream connection. Emits scan pipeline events (see server/internal/events/scan_events.md), app notifications (integrations, sync, plugin exit, coarse errors; see server/internal/events/notification_events.md), and save-sync migration lifecycle events (`save_sync_migration_started`, `save_sync_migration_progress`, `save_sync_migration_completed`, `save_sync_migration_failed`). Scan payloads include `job_id` so clients can recover in-progress jobs after reload. Each data line is JSON; map payloads include a ts field (RFC3339) when the publisher includes one.",
			ResponseDocs: map[string]string{
				"200": "text/event-stream; connection stays open until client disconnect or server shutdown",
				"500": "Streaming not supported",
			},
		},
		{
			Method:       "GET",
			Path:         "/api/save-sync/domains/{domain_id}/history",
			Summary:      "List retained saves for one Save Domain",
			Description:  "Returns the active profile's bounded, server-accepted history for one exact Save Domain. Evidence contains safe origin and route labels; it never exposes local paths, file names, endpoint identifiers, credentials, or another profile's data.",
			ResponseDocs: map[string]string{"200": "SaveDomainHistory JSON", "400": "Invalid domain or profile context", "500": "Internal server error"},
		},
		{
			Method:         "PUT",
			Path:           "/api/save-sync/domains/{domain_id}/history-policy",
			Summary:        "Set retention for one Save Domain",
			Description:    "Sets active-profile retention and immediately prunes older metadata and server-local payloads. Supported bounds are 1–50 versions and 1–365 days.",
			RequestBodyDoc: "JSON: { retain_versions: number, retain_days: number }",
			ResponseDocs:   map[string]string{"200": "Updated SaveDomainHistory JSON", "400": "Invalid domain, profile context, or retention bounds", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/save-sync/history/{version_id}/recover",
			Summary:        "Restore a retained Save Domain version",
			Description:    "Restores one version owned by the active profile. MGA retains the current save before promotion and then queues the normal provider upload; a failed activation preserves the current snapshot.",
			RequestBodyDoc: "Empty JSON object",
			ResponseDocs:   map[string]string{"202": "SaveSyncPutResult JSON", "400": "Invalid version or profile context", "409": "Version unavailable, invalid, or recovery failed", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/save-sync/migrations",
			Summary:        "Start a save-sync migration job",
			Description:    "Starts a background save migration from one save-sync integration to another. Supports `scope=all` or `scope=game`; `game` requires `canonical_game_id`. Progress and completion arrive over SSE and can also be polled by job id.",
			RequestBodyDoc: "JSON: { source_integration_id, target_integration_id, scope: \"all\"|\"game\", canonical_game_id?, delete_source_after_success? }",
			ResponseDocs:   map[string]string{"202": "SaveSyncMigrationStatus JSON", "400": "Invalid request body or unsupported scope", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/save-sync/migrations/{job_id}",
			Summary:      "Get save-sync migration job status",
			Description:  "Returns the latest in-memory status for a save-sync migration job, including counts for total, completed, migrated, skipped, and any terminal error.",
			ResponseDocs: map[string]string{"200": "SaveSyncMigrationStatus JSON", "404": "Unknown job id", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/save-sync/prefetch/{job_id}",
			Summary:      "Get save-sync prefetch job status",
			Description:  "Returns the latest in-memory status for a save-sync prefetch job, including progress, cached/missing/failed slot counts, and any terminal error.",
			ResponseDocs: map[string]string{"200": "SaveSyncPrefetchStatus JSON", "404": "Unknown job id", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/client-launches",
			Summary:        "Start the selected MGA Client mode",
			Description:    "Creates a short-lived signed browser-to-client launch challenge. Standard is the default; elevated requests require the local Windows user to approve UAC before the client redeems the challenge.",
			RequestBodyDoc: "JSON: { execution_mode?: 'standard' | 'elevated' }",
			ResponseDocs:   map[string]string{"201": "Client launch challenge JSON", "400": "Invalid execution mode", "401": "Profile sign-in required", "403": "Manage access required", "500": "Internal server error"},
		},
		{
			Method:      "GET",
			Path:        "/api/play/devices/{id}/installed-games",
			Summary:     "List installed games for the selected device",
			Description: "Returns the active profile's installed-only, canonically deduplicated shelf for one explicitly selected authorized device. Failed or attention states are excluded and counted; can_play reflects access, live compatibility, launch capability, and recorded target.",
			ResponseDocs: map[string]string{
				"200": "InstalledGamesResponse JSON",
				"400": "Invalid device id",
				"401": "Profile sign-in required",
				"404": "Device not found or not authorized for the active profile",
				"500": "Internal server error",
			},
		},
		{
			Method:       "GET",
			Path:         "/api/devices/validation-schedule",
			Summary:      "Get automatic installed-game check status",
			Description:  "Returns the active profile's schedule and per-device visibility for the shared manual/background MGA installation validator.",
			ResponseDocs: map[string]string{"200": "InstallationValidationScheduleStatus JSON", "401": "Profile sign-in required", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/install-preferences/profile",
			Summary:      "Get the active player's install folder",
			Description:  "Returns the active profile default and effective destination-root template. Environment variables are expanded only by MGA Client on the selected device/user endpoint.",
			ResponseDocs: map[string]string{"200": "InstallPreference JSON", "401": "Profile sign-in required", "500": "Internal server error"},
		},
		{
			Method:         "PUT",
			Path:           "/api/install-preferences/profile",
			Summary:        "Set the active player's install folder",
			Description:    "Stores the profile-scoped destination-root template. An empty template restores the standard %USERPROFILE%\\Games fallback.",
			RequestBodyDoc: "JSON: { root_template: string }",
			ResponseDocs:   map[string]string{"200": "InstallPreference JSON", "400": "Invalid template", "401": "Profile sign-in required", "500": "Internal server error"},
		},
		{
			Method:       "GET",
			Path:         "/api/devices/{id}/install-preference",
			Summary:      "Get a device/user install folder",
			Description:  "Returns the endpoint override, active profile default, effective template, and provenance for an authorized endpoint.",
			ResponseDocs: map[string]string{"200": "InstallPreference JSON", "401": "Profile sign-in required", "403": "View access required", "404": "Device not found", "500": "Internal server error"},
		},
		{
			Method:         "PUT",
			Path:           "/api/devices/{id}/install-preference",
			Summary:        "Set a device/user install folder",
			Description:    "Sets an Owner-authorized endpoint override. An empty template restores inheritance from the active profile.",
			RequestBodyDoc: "JSON: { root_template: string }",
			ResponseDocs:   map[string]string{"200": "InstallPreference JSON", "400": "Invalid template", "401": "Profile sign-in required", "403": "Owner access required", "404": "Device not found", "500": "Internal server error"},
		},
		{
			Method:         "PUT",
			Path:           "/api/devices/validation-schedule",
			Summary:        "Configure automatic installed-game checks",
			Description:    "Enables or pauses profile-scoped automatic validation and selects an interval from 5 minutes through 24 hours.",
			RequestBodyDoc: "JSON: { enabled: boolean, interval_minutes: number }",
			ResponseDocs:   map[string]string{"200": "InstallationValidationScheduleStatus JSON", "400": "Invalid interval", "401": "Profile sign-in required", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/{id}/validate-installations",
			Summary:        "Check MGA-installed games on a device",
			Description:    "Dispatches the same bounded, read-only typed installation validator used by automatic checks. It never deletes or repairs files or registry entries.",
			RequestBodyDoc: "Empty JSON object",
			ResponseDocs:   map[string]string{"202": "DeviceCommand JSON", "400": "No eligible installations or device not ready", "403": "View access required", "404": "Device not found", "409": "Device unavailable or incompatible", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/{id}/games/{game_id}/install-gog-inno",
			Summary:        "Install a verified GOG game on a device",
			Description:    "Creates a typed GOG Inno install command from the selected server-owned source package. The authenticated Manage action is installation consent; MGA Client verifies the publisher and package family and may still trigger Windows UAC, but does not show a separate install-confirmation popup.",
			RequestBodyDoc: "JSON: { source_game_id: string, destination_root?: string }",
			ResponseDocs:   map[string]string{"202": "DeviceCommand JSON", "400": "Invalid request or unsupported package", "404": "Device, game, or source not found", "409": "Device unavailable or installation state conflicts", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/{id}/games/{game_id}/use-existing",
			Summary:        "Use an existing installation for this game",
			Description:    "Requests a launch-only grant for one client-local installation. MGA Client verifies local evidence and requires confirmation on the device; the server receives no update, repair, cleanup, or uninstall authority.",
			RequestBodyDoc: "JSON: { source_game_id: string, local_installation_id: string }",
			ResponseDocs:   map[string]string{"202": "DeviceCommand JSON", "400": "Invalid game/source selection", "403": "Manage access required", "404": "Device or game not found", "409": "Device unavailable or client does not support local reuse", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/{id}/games/{game_id}/sources/{source_game_id}/use-storefront",
			Summary:        "Allow this profile to use an installed storefront copy",
			Description:    "Requests a profile- and binding-scoped launch-only grant for an exactly identified storefront product observed on the selected device. The storefront retains install, update, repair, and uninstall authority, and MGA Client requires native confirmation.",
			RequestBodyDoc: "Empty JSON object",
			ResponseDocs:   map[string]string{"202": "DeviceCommand JSON", "400": "Source is not an observed storefront product", "403": "Manage access required", "404": "Device, game, or source not found", "409": "Device unavailable or storefront reuse unsupported", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/{id}/games/{game_id}/sources/{source_game_id}/launch-storefront",
			Summary:        "Start a granted storefront copy",
			Description:    "Starts an exactly identified storefront product after MGA Client revalidates both the profile-scoped launch-only grant and current local installation evidence. The client constructs the provider URI; arbitrary launch targets are never accepted from the server.",
			RequestBodyDoc: "Empty JSON object",
			ResponseDocs:   map[string]string{"202": "DeviceCommand JSON", "400": "Source is not an observed storefront product", "403": "Play access required", "404": "Device, game, or source not found", "409": "Device unavailable, launch unsupported, or confirmation is missing", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/{id}/games/{game_id}/sources/{source_game_id}/uninstall",
			Summary:        "Uninstall a managed game from a device",
			Description:    "Dispatches the installation-family-specific typed uninstall command using only persisted installation evidence. GOG Inno uninstall uses the recorded publisher uninstaller and retains native destructive confirmation.",
			RequestBodyDoc: "Empty JSON object",
			ResponseDocs:   map[string]string{"202": "DeviceCommand JSON", "400": "Invalid request", "403": "Manage access required", "404": "Installation not found", "409": "Device unavailable or uninstall unsupported", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/{id}/games/{game_id}/sources/{source_game_id}/repair",
			Summary:        "Repair a managed game's launch details",
			Description:    "Asks the selected MGA Client to rediscover an unambiguous executable inside the exact managed installation boundary. It updates only MGA metadata, never downloads or deletes game files, and fails closed when local evidence is ambiguous.",
			RequestBodyDoc: "Empty JSON object",
			ResponseDocs:   map[string]string{"202": "DeviceCommand JSON", "400": "Installation is not eligible for repair", "403": "Manage access required", "404": "Installation not found", "409": "Device unavailable, client too old, or local evidence is ambiguous", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/{id}/games/{game_id}/sources/{source_game_id}/reinstall",
			Summary:        "Prepare a missing managed game for reinstall",
			Description:    "After native confirmation on the device, releases only a verified missing installation record so the normal install flow can start again. It never overwrites an existing installation or deletes remaining files.",
			RequestBodyDoc: "Empty JSON object",
			ResponseDocs:   map[string]string{"202": "DeviceCommand JSON", "400": "Installation is not eligible for reinstall", "403": "Manage access required", "404": "Installation not found", "409": "Device unavailable, client too old, or local ownership cannot be proven", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/{id}/games/{game_id}/sources/{source_game_id}/cleanup",
			Summary:        "Clean up a broken managed installation",
			Description:    "After native confirmation on the device, removes only an installation whose exact MGA-managed boundary can be proven. Publisher uninstallers are preferred where applicable; shared prerequisites, saves, and content outside the boundary are preserved.",
			RequestBodyDoc: "Empty JSON object",
			ResponseDocs:   map[string]string{"202": "DeviceCommand JSON", "400": "Installation is not eligible for cleanup", "403": "Manage access required", "404": "Installation not found", "409": "Device unavailable, client too old, or a safe managed boundary cannot be proven", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/{id}/games/{game_id}/sources/{source_game_id}/forget",
			Summary:        "Forget MGA ownership without deleting game files",
			Description:    "After native confirmation on the device, releases the verified MGA ownership record and retires the server's active installation row. No game files are deleted, so another MGA server can adopt the installation later.",
			RequestBodyDoc: "Empty JSON object",
			ResponseDocs:   map[string]string{"202": "DeviceCommand JSON", "400": "Installation is not eligible to be forgotten", "403": "Manage access required", "404": "Installation not found", "409": "Device unavailable, client too old, or local ownership cannot be proven", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/{id}/games/{game_id}/sources/{source_game_id}/cleanup-failed",
			Summary:        "Clean up a marked failed GOG installation",
			Description:    "Dispatches a typed cleanup command built only from persisted failed-install identity, boundary, hash, marker, and optional publisher-uninstaller evidence. Cleanup is unavailable for legacy attention rows without a marker.",
			RequestBodyDoc: "Empty JSON object",
			ResponseDocs:   map[string]string{"202": "DeviceCommand JSON", "400": "Invalid request", "403": "Manage access required", "404": "Installation not found", "409": "No verified cleanup marker or invalid state", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/{id}/games/{game_id}/sources/{source_game_id}/ignore-failed",
			Summary:        "Ignore a failed installation",
			Description:    "Records the authenticated profile and time, leaves files untouched, keeps Play blocked, and suppresses the active cleanup warning. This server-only state change never dispatches a device command.",
			RequestBodyDoc: "Empty JSON object",
			ResponseDocs:   map[string]string{"200": "Updated DeviceGameInstallation JSON", "400": "Invalid request", "403": "Manage access required", "404": "Installation not found", "409": "Invalid installation state", "500": "Internal server error"},
		},
		{
			Method:         "POST",
			Path:           "/api/devices/{id}/games/{game_id}/sources/{source_game_id}/reopen-failed-cleanup",
			Summary:        "Reopen an ignored failed installation",
			Description:    "Reverses Ignore and restores cleanup-required when a valid marker exists or attention-required for a legacy no-marker row. This server-only state change never dispatches a device command.",
			RequestBodyDoc: "Empty JSON object",
			ResponseDocs:   map[string]string{"200": "Updated DeviceGameInstallation JSON", "400": "Invalid request", "403": "Manage access required", "404": "Installation not found", "409": "Invalid installation state", "500": "Internal server error"},
		},
		// Scoped Frontend API v1. Every route below is authorized by a bearer
		// token issued to one profile with an explicit scope set; no session
		// cookie is involved, and no administrator capability is reachable.
		{
			Method:       "GET",
			Path:         "/api/frontend/v1/capabilities",
			Summary:      "Discover what this frontend API client can reach",
			Description:  "Returns the API version, the calling client identity and scopes, and the mounted feature catalog split into what the scopes unlock and what they do not. The unavailable list names the scope each withheld feature needs, so a frontend can request the right permission instead of guessing from a 403. Requires a valid bearer token but no particular scope.",
			ResponseDocs: map[string]string{"200": "Capability document JSON", "401": "Missing, unknown, revoked, or expired bearer token", "403": "Another profile was named in the header or query"},
		},
		{
			Method:       "GET",
			Path:         "/api/frontend/v1/games",
			Summary:      "List the calling profile library",
			Description:  "Same projection the management console reads, authorized by scope catalog.read. Profile scope comes from the token; naming another profile is refused rather than ignored.",
			ResponseDocs: map[string]string{"200": "Game list JSON", "401": "Missing or invalid bearer token", "403": "Token lacks catalog.read, or named another profile"},
		},
		{
			Method:       "GET",
			Path:         "/api/frontend/v1/games/{id}",
			Summary:      "Read one canonical game",
			Description:  "Requires scope catalog.read. The id is the stable canonical game id an external frontend maps its own records onto.",
			ResponseDocs: map[string]string{"200": "Game JSON", "401": "Missing or invalid bearer token", "403": "Token lacks catalog.read", "404": "Game not found for this profile"},
		},
		{
			Method:       "GET",
			Path:         "/api/frontend/v1/games/{id}/detail",
			Summary:      "Read one game with sources, media and file metadata",
			Description:  "Requires scope catalog.read. Includes the stable file ids the content routes accept, so a frontend can go from a library row to a download without a second discovery step.",
			ResponseDocs: map[string]string{"200": "Game detail JSON", "401": "Missing or invalid bearer token", "403": "Token lacks catalog.read", "404": "Game not found for this profile"},
		},
		{
			Method:       "GET",
			Path:         "/api/frontend/v1/catalog/offers",
			Summary:      "List catalog offers with entitlement and availability",
			Description:  "Requires scope catalog.read. Entitlement, availability and delivery are independent fields: unknown entitlement is not ownership, and unknown availability is not removal. This is how a frontend distinguishes a title that must be purchased from one that is no longer available.",
			ResponseDocs: map[string]string{"200": "Offer list JSON", "401": "Missing or invalid bearer token", "403": "Token lacks catalog.read"},
		},
		{
			Method:       "GET",
			Path:         "/api/frontend/v1/catalog/offers/{offer_id}",
			Summary:      "Read one catalog offer",
			Description:  "Requires scope catalog.read.",
			ResponseDocs: map[string]string{"200": "Offer JSON", "401": "Missing or invalid bearer token", "403": "Token lacks catalog.read", "404": "Offer not found for this profile"},
		},
		{
			Method:       "GET",
			Path:         "/api/frontend/v1/catalog/offers/{offer_id}/history",
			Summary:      "Read the observation history for one offer",
			Description:  "Requires scope catalog.read. Observations are historical evidence: a provider failure preserves last-good state and marks it stale rather than synthesizing an unavailable transition.",
			ResponseDocs: map[string]string{"200": "Observation history JSON", "401": "Missing or invalid bearer token", "403": "Token lacks catalog.read", "404": "Offer not found for this profile"},
		},
		{
			Method:       "GET",
			Path:         "/api/frontend/v1/media/{assetID}",
			Summary:      "Fetch one media asset",
			Description:  "Requires scope metadata.read. Served through http.ServeContent, so Range, HEAD and If-None-Match behave as they do for the console. The URL carries no credential: authorization is the bearer token on the request.",
			ResponseDocs: map[string]string{"200": "Binary media stream", "206": "Partial content for a Range request", "304": "Not modified", "401": "Missing or invalid bearer token", "403": "Token lacks metadata.read", "404": "Asset not found for this profile"},
		},
		{
			Method:       "GET",
			Path:         "/api/frontend/v1/content/copies/{copy_id}/manifest",
			Summary:      "Read the file manifest for one concrete copy",
			Description:  "Requires scope content.read. Names stable opaque file ids with their sizes and checksums where available. A frontend never names a server path; it names a file id from this manifest and the server resolves the source internally.",
			ResponseDocs: map[string]string{"200": "Manifest JSON", "304": "Not modified", "401": "Missing or invalid bearer token", "403": "Token lacks content.read", "404": "Copy not found for this profile", "409": "Source content is not ready; prepare a materialization first"},
		},
		{
			Method:       "GET",
			Path:         "/api/frontend/v1/content/copies/{copy_id}/files/{file_id}",
			Summary:      "Download one file from a concrete copy",
			Description:  "Requires scope content.read. Supports GET, HEAD and single-range requests via http.ServeContent; multiple ranges in one request are refused with 416 so resume behaviour stays predictable. Concurrent streams are limited per profile.",
			ResponseDocs: map[string]string{"200": "Binary stream", "206": "Partial content for a Range request", "304": "Not modified", "400": "Invalid copy or file id", "401": "Missing or invalid bearer token", "403": "Token lacks content.read", "404": "File not found for this profile", "416": "More than one byte range requested", "429": "Too many concurrent content streams for this profile"},
		},
		{
			Method:         "POST",
			Path:           "/api/frontend/v1/content/copies/{copy_id}/materializations",
			Summary:        "Prepare a remote copy for delivery",
			Description:    "Requires scope content.prepare, deliberately separate from content.read: materialization spends server storage, so a read-only frontend cannot trigger it. Direct local sources may return an immediately completed job.",
			RequestBodyDoc: "JSON materialization request; an empty object is accepted",
			ResponseDocs:   map[string]string{"200": "Materialization already complete", "202": "Materialization accepted", "401": "Missing or invalid bearer token", "403": "Token lacks content.prepare", "404": "Copy not found for this profile"},
		},
		{
			Method:       "GET",
			Path:         "/api/frontend/v1/content/materializations/{job_id}",
			Summary:      "Check materialization progress",
			Description:  "Requires scope content.prepare.",
			ResponseDocs: map[string]string{"200": "Materialization job JSON", "401": "Missing or invalid bearer token", "403": "Token lacks content.prepare", "404": "Job not found for this profile"},
		},
		{
			Method:         "POST",
			Path:           "/api/frontend/v1/content/materializations/{job_id}/cancel",
			Summary:        "Cancel a materialization",
			Description:    "Requires scope content.prepare. Cancelling stops further work and never deletes already-delivered content.",
			RequestBodyDoc: "Empty JSON object",
			ResponseDocs:   map[string]string{"200": "Updated materialization job JSON", "401": "Missing or invalid bearer token", "403": "Token lacks content.prepare", "404": "Job not found for this profile", "409": "Job is not cancellable"},
		},
	}
}
