package http

import (
	"net/http"
	"time"

	"github.com/GreenFuze/MyGamesAnywhere/server/internal/auth"
	"github.com/GreenFuze/MyGamesAnywhere/server/internal/core"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
)

// RouteBuilder holds controller references for building the HTTP router.
// If nil is passed to BuildRouter, routes are registered with no-op handlers for OpenAPI discovery.
type RouteBuilder struct {
	GameCtrl               *GameController
	MediaCtrl              *MediaController
	DiscoCtrl              *DiscoveryController
	AboutCtrl              *AboutController
	ConfigCtrl             *ConfigController
	PluginCtrl             *PluginController
	IntegrationRefreshCtrl *IntegrationRefreshController
	ReviewCtrl             *ReviewController
	AchievementCtrl        *AchievementController
	AchievementRefreshCtrl *AchievementRefreshController
	SyncCtrl               *SyncController
	UpdateCtrl             *UpdateController
	SaveSyncCtrl           *SaveSyncController
	CacheCtrl              *CacheController
	SSECtrl                *SSEController
	OAuthCtrl              *OAuthController
	ProfileCtrl            *ProfileController
	ProfileRepo            core.ProfileRepository
	AuthCtrl               *AuthController
	AuthService            *auth.Service
	DeviceCtrl             *DeviceController
}

func noopHandler() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {}
}

// BuildRouter builds the public API router. If b is nil, all routes use no-op handlers.
// spaStaticDir is optional: if non-empty and contains index.html, registers /* for the SPA.
func BuildRouter(b *RouteBuilder, middlewareTimeout time.Duration, spaStaticDir string) chi.Router {
	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	if b != nil {
		r.Get("/health", func(w http.ResponseWriter, r *http.Request) { w.Write([]byte("OK")) })
		r.Get("/auth/google/callback/{plugin_id}", b.OAuthCtrl.Callback)
		r.Get("/auth/xbox/callback", b.OAuthCtrl.XboxCallback)
	} else {
		r.Get("/health", noopHandler())
		r.Get("/auth/google/callback/{plugin_id}", noopHandler())
		r.Get("/auth/xbox/callback", noopHandler())
	}

	r.Route("/api", func(api chi.Router) {
		if b != nil {
			api.Get("/auth/session", b.AuthCtrl.Session)
			api.Post("/auth/login", b.AuthCtrl.Login)
			api.Post("/auth/logout", b.AuthCtrl.Logout)
			api.Put("/auth/credential", b.AuthCtrl.ChangeCredential)
			api.With(ProfileContextMiddleware(b.ProfileRepo)).Get("/auth/credential", b.AuthCtrl.CredentialStatus)
			api.With(ProfileContextMiddleware(b.ProfileRepo)).Post("/auth/credential", b.AuthCtrl.InitializeCredential)
			api.With(ProfileContextMiddleware(b.ProfileRepo)).Delete("/auth/credential", b.AuthCtrl.RemoveCredential)
			api.Post("/devices/pair", b.DeviceCtrl.Pair)
			api.Post("/devices/client-launches/redeem", b.DeviceCtrl.RedeemClientLaunch)
			api.Get("/devices/connect", b.DeviceCtrl.Connect)
			api.Get("/devices/client-download", b.DeviceCtrl.ClientDownload)
			api.Get("/devices/client-installer", b.DeviceCtrl.ServeClientInstaller)
			api.Head("/devices/client-installer", b.DeviceCtrl.ServeClientInstaller)
			api.Get("/device-transfers/archive", b.DeviceCtrl.ServeArchiveTransfer)
			api.Head("/device-transfers/archive", b.DeviceCtrl.ServeArchiveTransfer)
			api.Get("/device-transfers/content", b.DeviceCtrl.ServeArchiveTransfer)
			api.Head("/device-transfers/content", b.DeviceCtrl.ServeArchiveTransfer)
			api.Get("/device-transfers/save-domain", b.DeviceCtrl.ServeSaveDomainTransfer)
			api.Put("/device-transfers/save-domain", b.DeviceCtrl.ServeSaveDomainTransfer)
			api.Get("/setup/status", b.ProfileCtrl.SetupStatus)
			api.Post("/setup/start-fresh", b.ProfileCtrl.StartFresh)
			api.Post("/setup/restore-sync/check", b.ProfileCtrl.CheckRestoreSync)
			api.Post("/setup/restore-sync/browse", b.ProfileCtrl.BrowseRestoreSync)
			api.Post("/setup/restore-sync/points", b.ProfileCtrl.RestoreSyncPoints)
			api.Post("/setup/restore-sync", b.ProfileCtrl.RestoreSync)
			api.Get("/profiles", b.ProfileCtrl.ListProfiles)
			api.Get("/media/{assetID}", b.MediaCtrl.ServeMedia)
			api.Get("/auth/callback/{plugin_id}", b.OAuthCtrl.Callback)
			api.Post("/auth/callback/import", b.OAuthCtrl.ImportCallback)
			api.Put("/media/{assetID}/metadata", ProfileContextMiddleware(b.ProfileRepo)(RequireAdminProfile(http.HandlerFunc(b.MediaCtrl.UpdateMediaMetadata))).ServeHTTP)
			api.Get("/about", b.AboutCtrl.GetAbout)
			api.Get("/about/license", b.AboutCtrl.GetLicense)

			adminOnly := func(h http.HandlerFunc) http.HandlerFunc {
				return RequireAdminProfile(http.HandlerFunc(h)).ServeHTTP
			}

			api.With(ProfileContextMiddleware(b.ProfileRepo)).Post("/games/sources/delete-batch", adminOnly(b.GameCtrl.DeleteSourceGames))

			api.Group(func(r chi.Router) {
				r.Use(ProfileContextMiddleware(b.ProfileRepo))
				r.Use(RequireDeviceSession(b.AuthService))
				r.Get("/devices", b.DeviceCtrl.List)
				r.Get("/install-preferences/profile", b.DeviceCtrl.GetProfileInstallPreference)
				r.Put("/install-preferences/profile", b.DeviceCtrl.SetProfileInstallPreference)
				r.Get("/devices/validation-schedule", b.DeviceCtrl.GetInstallationValidationStatus)
				r.Put("/devices/validation-schedule", b.DeviceCtrl.SetInstallationValidationSchedule)
				r.Post("/devices/client-launches", b.DeviceCtrl.CreateClientLaunch)
				r.Get("/devices/client-launches/{id}", b.DeviceCtrl.GetClientLaunch)
				r.Post("/devices/pairing-challenges", b.DeviceCtrl.CreatePairingChallenge)
				r.Put("/devices/{id}", b.DeviceCtrl.Rename)
				r.Get("/devices/{id}/install-preference", b.DeviceCtrl.GetEndpointInstallPreference)
				r.Put("/devices/{id}/install-preference", b.DeviceCtrl.SetEndpointInstallPreference)
				r.Get("/devices/{id}/emulators", b.DeviceCtrl.GetEndpointEmulators)
				r.Put("/devices/{id}/emulators/{platform}/default", b.DeviceCtrl.SetEndpointEmulatorDefault)
				r.Put("/devices/{id}/emulators/{platform}/{emulator_id}/core", b.DeviceCtrl.SetEndpointEmulatorCore)
				r.Post("/devices/{id}/emulators/{emulator_id}/setup", b.DeviceCtrl.SetupEndpointEmulator)
				r.Delete("/devices/{id}", b.DeviceCtrl.Revoke)
				r.Get("/devices/{id}/grants", b.DeviceCtrl.ListGrants)
				r.Put("/devices/{id}/grants/{profile_id}", b.DeviceCtrl.SetGrant)
				r.Delete("/devices/{id}/grants/{profile_id}", b.DeviceCtrl.DeleteGrant)
				r.Post("/devices/{id}/commands", b.DeviceCtrl.DispatchCommand)
				r.Get("/devices/{id}/commands", b.DeviceCtrl.ListCommands)
				r.Post("/devices/{id}/validate-installations", b.DeviceCtrl.ValidateInstallations)
				r.Post("/devices/{id}/games/{game_id}/installation-preflight", b.DeviceCtrl.PreflightInstallation)
				r.Post("/devices/{id}/games/{game_id}/install-archive", b.DeviceCtrl.InstallArchive)
				r.Post("/devices/{id}/games/{game_id}/install-gog-inno", b.DeviceCtrl.InstallGogInno)
				r.Post("/devices/{id}/games/{game_id}/use-existing", b.DeviceCtrl.UseExistingInstallation)
				r.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/uninstall", b.DeviceCtrl.UninstallGame)
				r.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/cleanup-failed", b.DeviceCtrl.CleanupFailedGogInno)
				r.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/ignore-failed", b.DeviceCtrl.IgnoreFailedGogInno)
				r.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/reopen-failed-cleanup", b.DeviceCtrl.ReopenFailedGogInno)
				r.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/launch", b.DeviceCtrl.LaunchGame)
				r.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/launch-emulator", b.DeviceCtrl.LaunchEmulatorGame)
				r.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/save-domain/claim", b.DeviceCtrl.ClaimScummVMSaveDomain)
				r.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/save-domain/release", b.DeviceCtrl.ReleaseSaveDomain)
				r.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/save-domain/snapshot", b.DeviceCtrl.SnapshotSaveDomain)
				r.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/save-domain/restore", b.DeviceCtrl.RestoreSaveDomain)
				r.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/save-domain/reconcile", b.DeviceCtrl.ReconcileSaveDomain)
				r.Put("/devices/{id}/games/{game_id}/sources/{source_game_id}/launch-target", b.DeviceCtrl.SetLaunchTarget)
				r.Get("/play/devices/{id}/installed-games", b.GameCtrl.ListInstalledGames)
			})

			// Routes with standard middleware timeout.
			api.Group(func(r chi.Router) {
				if middlewareTimeout > 0 {
					r.Use(middleware.Timeout(middlewareTimeout))
				}
				r.Use(ProfileContextMiddleware(b.ProfileRepo))
				r.Get("/games", b.GameCtrl.ListGames)
				r.Delete("/games", adminOnly(b.GameCtrl.DeleteAll))
				r.Get("/games/{id}/detail", b.GameCtrl.GetDetail)
				r.Post("/games/{id}/refresh-metadata", adminOnly(b.GameCtrl.RefreshMetadata))
				r.Put("/games/{id}/cover-override", b.GameCtrl.SetCoverOverride)
				r.Delete("/games/{id}/cover-override", b.GameCtrl.ClearCoverOverride)
				r.Put("/games/{id}/hover-override", b.GameCtrl.SetHoverOverride)
				r.Put("/games/{id}/background-override", b.GameCtrl.SetBackgroundOverride)
				r.Put("/games/{id}/favorite", b.GameCtrl.SetFavorite)
				r.Delete("/games/{id}/favorite", b.GameCtrl.ClearFavorite)
				r.Post("/games/{id}/sources/{source_game_id}/delete-preview", b.GameCtrl.PreviewDeleteSourceGame)
				r.Delete("/games/{id}/sources/{source_game_id}", b.GameCtrl.DeleteSourceGame)
				r.Post("/games/{id}/sources/{source_game_id}/canonical/split", adminOnly(b.GameCtrl.SplitSourceGameCanonical))
				r.Post("/games/{id}/sources/{source_game_id}/canonical/merge", adminOnly(b.GameCtrl.MergeSourceGameCanonical))
				r.Delete("/games/{id}/sources/{source_game_id}/canonical-pin", adminOnly(b.GameCtrl.ClearSourceGameCanonicalPin))
				r.Get("/canonical-games/search", adminOnly(b.GameCtrl.SearchCanonicalGames))
				r.Post("/games/{id}/cache/prepare", b.CacheCtrl.PrepareGameCache)
				r.Post("/games/{id}/save-sync/prefetch", b.SaveSyncCtrl.StartPrefetch)
				r.Get("/games/{id}/save-sync/slots", b.SaveSyncCtrl.ListSlots)
				r.Get("/games/{id}/save-sync/slots/{slot_id}", b.SaveSyncCtrl.GetSlot)
				r.Put("/games/{id}/save-sync/slots/{slot_id}", b.SaveSyncCtrl.PutSlot)
				r.Get("/games/{id}", b.GameCtrl.Get)
				r.Get("/games/{id}/achievements", b.AchievementCtrl.GetAchievements)
				r.Get("/achievements", b.GameCtrl.AchievementsDashboard)
				r.Get("/achievements/explorer", b.GameCtrl.AchievementsExplorer)
				if b.AchievementRefreshCtrl != nil {
					r.Post("/achievements/refresh", adminOnly(b.AchievementRefreshCtrl.Start))
					r.Get("/achievements/refresh/jobs/{job_id}", adminOnly(b.AchievementRefreshCtrl.GetJob))
				}
				r.Get("/stats", b.GameCtrl.Stats)
				r.Get("/stats/library", b.GameCtrl.LibraryStatistics)
				r.Get("/stats/gamer", b.GameCtrl.GamerStatistics)
				r.Get("/duplicates/games", adminOnly(b.GameCtrl.DuplicateGames))
				r.Get("/config/frontend", adminOnly(b.ConfigCtrl.GetFrontend))
				r.Post("/config/frontend", adminOnly(b.ConfigCtrl.SetFrontend))
				r.Get("/plugins", adminOnly(b.PluginCtrl.ListPlugins))
				r.Get("/plugins/{plugin_id}", adminOnly(b.PluginCtrl.GetPluginByID))
				r.Post("/config/{key}", adminOnly(b.ConfigCtrl.Set))
				r.Post("/profiles", b.ProfileCtrl.CreateProfile)
				r.Put("/profiles/{id}", b.ProfileCtrl.UpdateProfile)
				r.Delete("/profiles/{id}", b.ProfileCtrl.DeleteProfile)
				r.Get("/integrations", adminOnly(b.PluginCtrl.List))
				r.Get("/integrations/status", adminOnly(b.PluginCtrl.Status))
				r.Post("/integrations", adminOnly(b.PluginCtrl.Create))
				r.Get("/integrations/{id}/status", adminOnly(b.PluginCtrl.StatusOne))
				r.Post("/integrations/{id}/authorize", adminOnly(b.PluginCtrl.StartIntegrationAuth))
				r.Post("/plugins/{plugin_id}/check-config", adminOnly(b.PluginCtrl.CheckPluginConfig))
				if b.IntegrationRefreshCtrl != nil {
					r.Post("/integrations/{id}/refresh", adminOnly(b.IntegrationRefreshCtrl.Start))
					r.Get("/integration-refresh/jobs/{job_id}", adminOnly(b.IntegrationRefreshCtrl.GetJob))
				} else {
					r.Post("/integrations/{id}/refresh", noopHandler())
					r.Get("/integration-refresh/jobs/{job_id}", noopHandler())
				}
				r.Get("/integrations/{id}/games", adminOnly(b.PluginCtrl.IntegrationGames))
				r.Get("/integrations/{id}/enriched-games", adminOnly(b.PluginCtrl.IntegrationEnrichedGames))
				r.Post("/integrations/{id}/validate-files", adminOnly(b.PluginCtrl.ValidateIntegrationFiles))
				r.Get("/review-candidates", adminOnly(b.ReviewCtrl.ListCandidates))
				r.Post("/review-candidates/redetect", adminOnly(b.ReviewCtrl.RedetectActive))
				r.Get("/review-candidates/{id}", adminOnly(b.ReviewCtrl.GetCandidate))
				r.Post("/review-candidates/{id}/search", adminOnly(b.ReviewCtrl.SearchCandidate))
				r.Post("/review-candidates/{id}/redetect", adminOnly(b.ReviewCtrl.RedetectCandidate))
				r.Post("/review-candidates/{id}/apply", adminOnly(b.ReviewCtrl.ApplyCandidate))
				r.Post("/review-candidates/{id}/not-a-game", adminOnly(b.ReviewCtrl.MarkCandidateNotAGame))
				r.Post("/review-candidates/{id}/dlc", adminOnly(b.ReviewCtrl.MarkCandidateDLC))
				r.Post("/review-candidates/{id}/base-game", adminOnly(b.ReviewCtrl.MarkCandidateBaseGame))
				r.Post("/review-candidates/{id}/unarchive", adminOnly(b.ReviewCtrl.UnarchiveCandidate))
				r.Post("/review-candidates/{id}/files/delete-preview", adminOnly(b.ReviewCtrl.PreviewDeleteCandidateFiles))
				r.Delete("/review-candidates/{id}/files", adminOnly(b.ReviewCtrl.DeleteCandidateFiles))
				r.Put("/integrations/{id}", adminOnly(b.PluginCtrl.UpdateIntegration))
				r.Delete("/integrations/{id}", adminOnly(b.PluginCtrl.DeleteIntegration))
				r.Post("/plugins/{plugin_id}/browse", adminOnly(b.PluginCtrl.Browse))

				r.Get("/sync/status", adminOnly(b.SyncCtrl.Status))
				r.Post("/sync/push", adminOnly(b.SyncCtrl.Push))
				r.Post("/sync/pull", adminOnly(b.SyncCtrl.Pull))
				r.Post("/sync/key", adminOnly(b.SyncCtrl.StoreKey))
				r.Delete("/sync/key", adminOnly(b.SyncCtrl.ClearKey))
				r.Get("/update/status", adminOnly(b.UpdateCtrl.Status))
				r.Post("/update/check", adminOnly(b.UpdateCtrl.Check))
				r.Post("/update/download", adminOnly(b.UpdateCtrl.Download))
				r.Post("/update/apply", adminOnly(b.UpdateCtrl.Apply))
				r.Get("/media/queue/status", adminOnly(b.MediaCtrl.QueueStatus))
				r.Post("/media/queue/retry-failed", adminOnly(b.MediaCtrl.RetryFailed))
				r.Post("/media/cache/clear", adminOnly(b.MediaCtrl.ClearCache))
				r.Post("/save-sync/migrations", adminOnly(b.SaveSyncCtrl.StartMigration))
				r.Get("/save-sync/migrations/{job_id}", adminOnly(b.SaveSyncCtrl.GetMigrationStatus))
				r.Get("/save-sync/prefetch/{job_id}", b.SaveSyncCtrl.GetPrefetchStatus)
				r.Get("/cache/jobs", adminOnly(b.CacheCtrl.ListJobs))
				r.Get("/cache/jobs/{job_id}", adminOnly(b.CacheCtrl.GetJob))
				r.Get("/cache/entries", adminOnly(b.CacheCtrl.ListEntries))
				r.Delete("/cache/entries/{entry_id}", adminOnly(b.CacheCtrl.DeleteEntry))
				r.Post("/cache/clear", adminOnly(b.CacheCtrl.Clear))

			})

			// Browser play streams can be large; enforce profile context without request timeout.
			api.Group(func(r chi.Router) {
				r.Use(ProfileContextMiddleware(b.ProfileRepo))
				r.Get("/games/{id}/play", b.GameCtrl.ServePlayFile)
				r.Head("/games/{id}/play", b.GameCtrl.ServePlayFile)
			})

			api.Group(func(r chi.Router) {
				r.Use(OptionalProfileContextMiddleware(b.ProfileRepo))
				r.Get("/events", b.SSECtrl.Events)
			})

			// Scan can take many minutes; no middleware timeout.
			api.Group(func(r chi.Router) {
				r.Use(ProfileContextMiddleware(b.ProfileRepo))
				r.Use(RequireAdminProfile)
				r.Get("/scan", b.DiscoCtrl.Scan)
				r.Post("/scan", b.DiscoCtrl.Scan)
				r.Get("/scan/jobs/{job_id}", b.DiscoCtrl.GetScanJob)
				r.Post("/scan/jobs/{job_id}/cancel", b.DiscoCtrl.CancelScanJob)
				r.Get("/scan/background", b.DiscoCtrl.GetBackgroundScanStatus)
				r.Put("/scan/background", b.DiscoCtrl.SetBackgroundScanConfig)
				r.Get("/scan/reports", b.DiscoCtrl.GetScanReports)
				r.Get("/scan/reports/{id}", b.DiscoCtrl.GetScanReport)
			})
		} else {
			api.Get("/auth/session", noopHandler())
			api.Post("/auth/login", noopHandler())
			api.Post("/auth/logout", noopHandler())
			api.Put("/auth/credential", noopHandler())
			api.Get("/auth/credential", noopHandler())
			api.Post("/auth/credential", noopHandler())
			api.Delete("/auth/credential", noopHandler())
			api.Post("/devices/pair", noopHandler())
			api.Post("/devices/client-launches/redeem", noopHandler())
			api.Get("/devices/connect", noopHandler())
			api.Get("/devices/client-download", noopHandler())
			api.Get("/devices/client-installer", noopHandler())
			api.Head("/devices/client-installer", noopHandler())
			api.Get("/device-transfers/archive", noopHandler())
			api.Head("/device-transfers/archive", noopHandler())
			api.Get("/device-transfers/content", noopHandler())
			api.Head("/device-transfers/content", noopHandler())
			api.Get("/device-transfers/save-domain", noopHandler())
			api.Put("/device-transfers/save-domain", noopHandler())
			api.Get("/devices", noopHandler())
			api.Get("/install-preferences/profile", noopHandler())
			api.Put("/install-preferences/profile", noopHandler())
			api.Get("/devices/validation-schedule", noopHandler())
			api.Put("/devices/validation-schedule", noopHandler())
			api.Post("/devices/pairing-challenges", noopHandler())
			api.Post("/devices/client-launches", noopHandler())
			api.Get("/devices/client-launches/{id}", noopHandler())
			api.Put("/devices/{id}", noopHandler())
			api.Get("/devices/{id}/install-preference", noopHandler())
			api.Put("/devices/{id}/install-preference", noopHandler())
			api.Delete("/devices/{id}", noopHandler())
			api.Get("/devices/{id}/grants", noopHandler())
			api.Put("/devices/{id}/grants/{profile_id}", noopHandler())
			api.Delete("/devices/{id}/grants/{profile_id}", noopHandler())
			api.Post("/devices/{id}/commands", noopHandler())
			api.Get("/devices/{id}/commands", noopHandler())
			api.Post("/devices/{id}/validate-installations", noopHandler())
			api.Post("/devices/{id}/games/{game_id}/install-archive", noopHandler())
			api.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/save-domain/claim", noopHandler())
			api.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/save-domain/release", noopHandler())
			api.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/save-domain/snapshot", noopHandler())
			api.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/save-domain/restore", noopHandler())
			api.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/save-domain/reconcile", noopHandler())
			api.Post("/devices/{id}/games/{game_id}/install-gog-inno", noopHandler())
			api.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/uninstall", noopHandler())
			api.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/cleanup-failed", noopHandler())
			api.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/ignore-failed", noopHandler())
			api.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/reopen-failed-cleanup", noopHandler())
			api.Post("/devices/{id}/games/{game_id}/sources/{source_game_id}/launch", noopHandler())
			api.Put("/devices/{id}/games/{game_id}/sources/{source_game_id}/launch-target", noopHandler())
			api.Get("/play/devices/{id}/installed-games", noopHandler())
			api.Get("/setup/status", noopHandler())
			api.Post("/setup/start-fresh", noopHandler())
			api.Post("/setup/restore-sync/check", noopHandler())
			api.Post("/setup/restore-sync/browse", noopHandler())
			api.Post("/setup/restore-sync/points", noopHandler())
			api.Post("/setup/restore-sync", noopHandler())
			api.Get("/profiles", noopHandler())
			api.Get("/auth/callback/{plugin_id}", noopHandler())
			api.Post("/auth/callback/import", noopHandler())
			api.Get("/games", noopHandler())
			api.Delete("/games", noopHandler())
			api.Get("/games/{id}/detail", noopHandler())
			api.Post("/games/{id}/refresh-metadata", noopHandler())
			api.Put("/games/{id}/cover-override", noopHandler())
			api.Delete("/games/{id}/cover-override", noopHandler())
			api.Put("/games/{id}/hover-override", noopHandler())
			api.Put("/games/{id}/background-override", noopHandler())
			api.Put("/games/{id}/favorite", noopHandler())
			api.Delete("/games/{id}/favorite", noopHandler())
			api.Post("/games/sources/delete-batch", noopHandler())
			api.Post("/games/{id}/sources/{source_game_id}/delete-preview", noopHandler())
			api.Delete("/games/{id}/sources/{source_game_id}", noopHandler())
			api.Get("/games/{id}/play", noopHandler())
			api.Head("/games/{id}/play", noopHandler())
			api.Post("/games/{id}/cache/prepare", noopHandler())
			api.Post("/games/{id}/save-sync/prefetch", noopHandler())
			api.Get("/games/{id}/save-sync/slots", noopHandler())
			api.Get("/games/{id}/save-sync/slots/{slot_id}", noopHandler())
			api.Put("/games/{id}/save-sync/slots/{slot_id}", noopHandler())
			api.Get("/games/{id}", noopHandler())
			api.Get("/games/{id}/achievements", noopHandler())
			api.Get("/achievements", noopHandler())
			api.Get("/achievements/explorer", noopHandler())
			api.Post("/achievements/refresh", noopHandler())
			api.Get("/achievements/refresh/jobs/{job_id}", noopHandler())
			api.Get("/media/{assetID}", noopHandler())
			api.Put("/media/{assetID}/metadata", noopHandler())
			api.Get("/stats", noopHandler())
			api.Get("/stats/library", noopHandler())
			api.Get("/stats/gamer", noopHandler())
			api.Get("/duplicates/games", noopHandler())
			api.Get("/about", noopHandler())
			api.Get("/about/license", noopHandler())
			api.Get("/config/frontend", noopHandler())
			api.Post("/config/frontend", noopHandler())
			api.Get("/scan", noopHandler())
			api.Post("/scan", noopHandler())
			api.Get("/scan/jobs/{job_id}", noopHandler())
			api.Post("/scan/jobs/{job_id}/cancel", noopHandler())
			api.Get("/scan/reports", noopHandler())
			api.Get("/scan/reports/{id}", noopHandler())
			api.Get("/scan/background", noopHandler())
			api.Put("/scan/background", noopHandler())
			api.Get("/plugins", noopHandler())
			api.Get("/plugins/{plugin_id}", noopHandler())
			api.Post("/config/{key}", noopHandler())
			api.Get("/integrations", noopHandler())
			api.Get("/integrations/status", noopHandler())
			api.Post("/integrations", noopHandler())
			api.Get("/integrations/{id}/status", noopHandler())
			api.Post("/integrations/{id}/authorize", noopHandler())
			api.Post("/plugins/{plugin_id}/check-config", noopHandler())
			api.Post("/integrations/{id}/refresh", noopHandler())
			api.Get("/integrations/{id}/games", noopHandler())
			api.Get("/integrations/{id}/enriched-games", noopHandler())
			api.Post("/integrations/{id}/validate-files", noopHandler())
			api.Get("/integration-refresh/jobs/{job_id}", noopHandler())
			api.Get("/review-candidates", noopHandler())
			api.Post("/review-candidates/redetect", noopHandler())
			api.Get("/review-candidates/{id}", noopHandler())
			api.Post("/review-candidates/{id}/search", noopHandler())
			api.Post("/review-candidates/{id}/redetect", noopHandler())
			api.Post("/review-candidates/{id}/apply", noopHandler())
			api.Post("/review-candidates/{id}/not-a-game", noopHandler())
			api.Post("/review-candidates/{id}/dlc", noopHandler())
			api.Post("/review-candidates/{id}/base-game", noopHandler())
			api.Post("/review-candidates/{id}/unarchive", noopHandler())
			api.Post("/review-candidates/{id}/files/delete-preview", noopHandler())
			api.Delete("/review-candidates/{id}/files", noopHandler())
			api.Put("/integrations/{id}", noopHandler())
			api.Delete("/integrations/{id}", noopHandler())
			api.Post("/plugins/{plugin_id}/browse", noopHandler())
			api.Get("/sync/status", noopHandler())
			api.Post("/sync/push", noopHandler())
			api.Post("/sync/pull", noopHandler())
			api.Post("/sync/key", noopHandler())
			api.Delete("/sync/key", noopHandler())
			api.Get("/update/status", noopHandler())
			api.Post("/update/check", noopHandler())
			api.Post("/update/download", noopHandler())
			api.Post("/update/apply", noopHandler())
			api.Get("/media/queue/status", noopHandler())
			api.Post("/media/queue/retry-failed", noopHandler())
			api.Post("/media/cache/clear", noopHandler())
			api.Post("/save-sync/migrations", noopHandler())
			api.Get("/save-sync/migrations/{job_id}", noopHandler())
			api.Get("/save-sync/prefetch/{job_id}", noopHandler())
			api.Get("/cache/jobs", noopHandler())
			api.Get("/cache/jobs/{job_id}", noopHandler())
			api.Get("/cache/entries", noopHandler())
			api.Delete("/cache/entries/{entry_id}", noopHandler())
			api.Post("/cache/clear", noopHandler())
			api.Get("/events", noopHandler())
		}
	})

	MountSPA(r, spaStaticDir)
	return r
}
