import { useQuery } from '@tanstack/react-query'
import { KeyRound, ServerCog, ShieldCheck } from 'lucide-react'
import { getAboutInfo, getHealth, listFrontendAPIClients } from '@/api/client'
import { MetricCard, PageIntro, QueryFeedback, SectionCard, StatusPill, formatCount, formatDate } from '@/components/management/ManagementPrimitives'
import { useProfiles } from '@/hooks/useProfiles'

export function SystemPage() {
  const { currentProfile } = useProfiles()
  const admin = currentProfile?.role === 'admin_player'
  const health = useQuery({ queryKey: ['management', 'health'], queryFn: getHealth })
  const about = useQuery({ queryKey: ['management', 'about'], queryFn: getAboutInfo })
  const clients = useQuery({ queryKey: ['management', 'frontend-clients'], queryFn: listFrontendAPIClients, enabled: admin })
  const activeClients = clients.data?.clients.filter((client) => !client.revoked_at).length ?? 0
  return <div className="mga-page-enter space-y-7">
    <PageIntro eyebrow="Server administration" title="System and frontend integrations" description="Inspect the Go control plane, scoped store-like API clients, compatibility retirement, and recovery evidence." />
    <div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Go server" value={health.isSuccess ? 'Online' : 'Unavailable'} detail={health.isSuccess ? 'Health endpoint is responding' : 'Health check has not succeeded'} tone={health.isSuccess ? 'good' : 'danger'} icon={<ServerCog className="h-4 w-4" />} /><MetricCard label="API clients" value={admin ? formatCount(activeClients) : 'Restricted'} detail={admin ? 'Active scoped frontend integrations' : 'Administrator role required'} icon={<KeyRound className="h-4 w-4" />} /><MetricCard label="Local execution" value="Retired" detail="Legacy client workflows return typed HTTP 410 responses" tone="good" icon={<ShieldCheck className="h-4 w-4" />} /></div>
    <div className="grid gap-5 xl:grid-cols-2">
      <SectionCard title="MGA server" description="Build identity and operating boundary."><QueryFeedback pending={about.isPending} error={about.error} empty={false} emptyTitle="" emptyDescription="" />{about.data && <dl className="grid grid-cols-[8rem_1fr] gap-x-4 gap-y-3 text-xs"><dt className="text-mga-muted">Version</dt><dd className="font-mono text-mga-text">{about.data.version || 'development'}</dd><dt className="text-mga-muted">Commit</dt><dd className="truncate font-mono text-mga-text">{about.data.commit || 'working tree'}</dd><dt className="text-mga-muted">Build date</dt><dd className="text-mga-text">{about.data.build_date || 'development build'}</dd><dt className="text-mga-muted">Serving model</dt><dd className="text-mga-text">Headless control plane + scoped frontend APIs</dd></dl>}</SectionCard>
      <SectionCard title="Frontend API clients" description="Tokens are profile-bound, scoped, revocable, and shown only to administrators.">{!admin ? <div className="rounded-lg border border-amber-400/20 bg-amber-400/5 p-4 text-xs leading-5 text-mga-muted">Switch to an administrator profile to manage external frontend clients.</div> : <><QueryFeedback pending={clients.isPending} error={clients.error} empty={!clients.isPending && (clients.data?.clients.length ?? 0) === 0} emptyTitle="No frontend clients issued" emptyDescription="Issue a scoped client when connecting Playnite or another approved desktop or mobile frontend." />{(clients.data?.clients.length ?? 0) > 0 && <div className="space-y-2">{clients.data?.clients.map((client) => <div key={client.id} className="rounded-lg border border-mga-border bg-mga-elevated/40 p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium text-mga-text">{client.name}</p><StatusPill label={client.revoked_at ? 'Revoked' : 'Active'} tone={client.revoked_at ? 'danger' : 'good'} /></div><p className="mt-2 text-xs text-mga-muted">{client.scopes.join(' · ')}</p><p className="mt-1 text-[0.68rem] text-mga-muted">Last used {formatDate(client.last_used_at)}</p></div>)}</div>}</>}</SectionCard>
    </div>
    {admin && <SectionCard title="Legacy client recovery" description="Read-only compatibility evidence is retained temporarily; no executor, command payload, or secret is exported."><div className="flex flex-col gap-3 rounded-lg border border-mga-border bg-mga-elevated/40 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium text-mga-text">Installation and endpoint report</p><p className="mt-1 text-xs leading-5 text-mga-muted">Available from the admin-only <code className="text-mga-accent">/api/legacy-client-data/report</code> endpoint. Legacy tables remain read-only during the compatibility window.</p></div><StatusPill label="Read only" tone="attention" /></div></SectionCard>}
  </div>
}
